import { cityBlogArticles } from "./city-blog-articles";

export const blogs = [
  ...cityBlogArticles.map(({ slug, category, title, description, image, imageAlt }) => ({
    slug, category, title, description, image, imageAlt, date: "2026-08-15", readTime: "18 min read",
  })),
  {
    slug: "vasishta-nadi-astrology", category: "Sages & lineages", title: "Vasishta Nadi Astrology: Sage, Dharma and Reading Guide",
    description: "Sage Vasishta, dharma and family themes, thumb-impression matching, remedies, evidence and careful verification.",
    image: "/images/blog-vasishta-nadi-astrology-real.webp", imageAlt: "1916 Chitra Ramayana illustration showing Sage Vasishta addressing Queen Kaikeyi", date: "2026-08-16", readTime: "18 min read",
  },
  {
    slug: "nandi-nadi-astrology", category: "Sages & lineages", title: "Nandi Nadi Astrology: Nandi, Shiva and Reading Guide",
    description: "Nandi's Shaiva tradition, the difference from Bhrigu Nandi Nadi, palm-leaf matching, themes, remedies and careful verification.",
    image: "/images/blog-nandi-nadi-astrology-real.webp", imageAlt: "Large granite Nandi statue at Lepakshi in Andhra Pradesh", date: "2026-08-15", readTime: "18 min read",
  },
  {
    slug: "shiva-vakya-nadi-astrology", category: "Sages & lineages", title: "Shiva Vakya Nadi Astrology: Tradition and Reading Guide",
    description: "The Shiva–Parvati dialogue tradition, personal-leaf claims, reading process, remedies and careful verification.",
    image: "/images/blog-shiva-vakya-nadi-astrology-real.webp", imageAlt: "Historic sculpture of Shiva and Parvati", date: "2026-08-15", readTime: "18 min read",
  },
  {
    slug: "brahma-nadi-astrology", category: "Sages & lineages", title: "Brahma Nadi Astrology: Creation, Destiny and Reading Guide",
    description: "Brahma attribution, destiny and life-purpose themes, manuscript claims, matching process and verification.",
    image: "/images/blog-brahma-nadi-astrology-real.webp", imageAlt: "Brahma Temple and shrine at Pushkar in Rajasthan", date: "2026-08-15", readTime: "18 min read",
  },
  {
    slug: "atri-nadi-astrology", category: "Sages & lineages", title: "Atri Nadi Astrology: Sage, Family Lineage and Reading Guide",
    description: "Maharishi Atri, Anasuya and Dattatreya associations, family-karma themes, matching and verification.",
    image: "/images/blog-atri-nadi-astrology-real.webp", imageAlt: "Dattatreya statue at Muktidham in Nashik", date: "2026-08-15", readTime: "18 min read",
  },
  {
    slug: "dhanvantari-nadi-astrology", category: "Sages & lineages", title: "Dhanvantari Nadi Astrology: Health Tradition and Safe Guide",
    description: "Dhanvantari's healing attribution, health and remedy themes, reading process, medical boundaries and verification.",
    image: "/images/blog-dhanvantari-nadi-astrology-real.webp", imageAlt: "Stone sculpture of Dhanvantari in Telangana", date: "2026-08-15", readTime: "18 min read",
  },
  {
    slug: "shukra-nadi-astrology", category: "Sages & lineages", title: "Shukra Nadi Astrology: Venus, Love and Prosperity Guide",
    description: "Venus and Shukracharya associations, relationship and prosperity themes, palm-leaf versus chart methods and verification.",
    image: "/images/blog-shukra-nadi-astrology-real.webp", imageAlt: "Navagraha temple at Khargone", date: "2026-08-15", readTime: "18 min read",
  },
  {
    slug: "kakabhushundi-nadi-astrology", category: "Sages & lineages", title: "Kakabhushundi Nadi Astrology: Crow Sage and Reading Guide",
    description: "The crow-sage tradition, Rama devotion, cycles and timing themes, reading process and verification.",
    image: "/images/blog-kakabhushundi-nadi-astrology-real.webp", imageAlt: "Historic painting of Kakabhushundi represented as a crow sage", date: "2026-08-15", readTime: "18 min read",
  },
  {
    slug: "bhogar-nadi-astrology",
    category: "Sages & lineages",
    title: "Bhogar Nadi Astrology: Siddha, Palani and Reading Guide",
    description:
      "Who Bhogar is, how Palani and Siddha literature relate to his tradition, what modern Bhogar Nadi readings claim and how to verify a leaf search.",
    image: "/images/blog-bhogar-nadi-astrology-real.webp",
    imageAlt: "Palani Murugan Hill Temple in Tamil Nadu, a sacred place associated with Bhogar in devotional tradition",
    date: "2026-08-14",
    readTime: "18 min read",
  },
  {
    slug: "thirumoolar-nadi-astrology",
    category: "Sages & lineages",
    title: "Thirumoolar Nadi Astrology: Sage, Text and Reading Guide",
    description:
      "Who Thirumoolar is, what the Tirumantiram documents, what modern Thirumoolar Nadi readings claim and how to approach a leaf search carefully.",
    image: "/images/blog-thirumoolar-nadi-astrology-real.webp",
    imageAlt: "Devotional image identified as Thirumoolar Nayanar seated in a Tamil temple setting",
    date: "2026-08-14",
    readTime: "18 min read",
  },
  {
    slug: "nadi-astrology-aasi-kandam",
    category: "Aasi Kandam",
    title: "Nadi Astrology Aasi Kandam: Blessing and Life Purpose",
    description: "Explore traditional blessing and life-purpose themes while protecting spiritual freedom, work, family, health and financial choice.",
    image: "/images/blog-nadi-astrology-aasi-kandam-real.webp",
    imageAlt: "Flower offerings at Patalganga Ghat in Srisailam",
    date: "2026-08-08",
    readTime: "17 min read",
  },
  {
    slug: "nadi-astrology-prasanna-kandam",
    category: "Prasanna Kandam",
    title: "Nadi Astrology Prasanna Kandam: Five-Question Guide",
    description:
      "Frame, record and review five focused questions while protecting privacy, evidence and ownership of every real-world decision.",
    image: "/images/blog-nadi-astrology-prasanna-kandam-real.webp",
    imageAlt: "A pen resting on an open lined notebook",
    date: "2026-08-08",
    readTime: "17 min read",
  },
  {
    slug: "nadi-astrology-political-kandam",
    category: "Political Kandam",
    title: "Nadi Astrology Political Kandam: Public Life Guide",
    description:
      "Understand traditional public-life claims while testing service, eligibility, funding, compliance, safety and candidacy with evidence.",
    image: "/images/blog-nadi-astrology-political-kandam-real.webp",
    imageAlt: "The Parliament House building in New Delhi",
    date: "2026-08-08",
    readTime: "17 min read",
  },
  {
    slug: "nadi-astrology-gnana-kandam",
    category: "Gnana Kandam",
    title: "Nadi Astrology Gnana Kandam: A Spiritual Guidance Guide",
    description:
      "Understand the traditional wisdom chapter while protecting choice, wellbeing, time, money and your freedom to question spiritual guidance.",
    image: "/images/blog-nadi-astrology-gnana-kandam-real.webp",
    imageAlt: "People meditating at the Mahabodhi Temple complex in Bodh Gaya",
    date: "2026-08-08",
    readTime: "18 min read",
  },
  {
    slug: "nadi-astrology-aushadha-kandam",
    category: "Aushadha Kandam",
    title: "Nadi Astrology Aushadha Kandam: Chapter 15 Guide",
    description:
      "Understand Chapter 15's traditional medicine guidance while checking diagnosis, practitioner, ingredients, dosage, interactions and adverse effects.",
    image: "/images/blog-nadi-astrology-aushadha-kandam-real.webp",
    imageAlt: "A collection of medicinal plants associated with Unani medicine in India",
    date: "2026-08-08",
    readTime: "18 min read",
  },
  {
    slug: "nadi-astrology-deeksha-kandam",
    category: "Deeksha Kandam",
    title: "Nadi Astrology Deeksha Kandam: Chapter 14 Guide",
    description:
      "Understand Chapter 14's traditional mantra and protection guidance while keeping initiation, consent, cost and spiritual authority clear.",
    image: "/images/blog-nadi-astrology-deeksha-kandam-real.webp",
    imageAlt: "Rows of colourful japa mala prayer beads displayed for sale in Varanasi",
    date: "2026-08-08",
    readTime: "18 min read",
  },
  {
    slug: "nadi-astrology-job-change-prediction",
    category: "Job-change readings",
    title: "Nadi Astrology Job Change Prediction: A Safe Switch Guide",
    description:
      "Understand traditional job-change timing claims, then compare offers, verify employers, plan notice and protect income before resigning.",
    image: "/images/blog-nadi-astrology-job-change-prediction-real.webp",
    imageAlt: "Two Indian men looking together at a laptop computer",
    date: "2026-08-08",
    readTime: "18 min read",
  },
  {
    slug: "nadi-astrology-debt-prediction",
    category: "Debt readings",
    title: "Nadi Astrology Debt Prediction: Kandam 6 Guide",
    description:
      "Understand traditional debt claims while building a verified repayment plan, checking lenders and keeping remedies outside your loan budget.",
    image: "/images/blog-nadi-astrology-debt-prediction-real.webp",
    imageAlt: "People gathered outside an Indian Bank branch in Sonia Vihar",
    date: "2026-08-08",
    readTime: "18 min read",
  },
  {
    slug: "nadi-astrology-second-marriage-prediction",
    category: "Remarriage readings",
    title: "Nadi Astrology Second Marriage Prediction: A Safe Guide",
    description:
      "Understand remarriage claims while protecting legal closure, grief, consent, children, finances and a future partner’s freedom.",
    image: "/images/blog-nadi-astrology-second-marriage-prediction-real.webp",
    imageAlt: "An Indian couple wearing wedding attire",
    date: "2026-08-08",
    readTime: "18 min read",
  },
  {
    slug: "nadi-astrology-mother-prediction",
    category: "Mother readings",
    title: "Nadi Astrology Mother Prediction: Kandam 4 Guide",
    description:
      "What Kandam 4 may say about mother, home and comfort—and how to protect consent, health decisions, caregiving and property evidence.",
    image: "/images/blog-nadi-astrology-mother-prediction-real.webp",
    imageAlt: "Mother holding a young child in a West Bengal village",
    date: "2026-08-08",
    readTime: "18 min read",
  },
  {
    slug: "nadi-astrology-business-prediction",
    category: "Business readings",
    title: "Nadi Astrology Business Prediction: A Decision-Safe Guide",
    description:
      "Translate business, partnership and timing claims into market tests, cash-flow limits, official checks and staged decisions without treating a leaf as a profit guarantee.",
    image: "/images/blog-nadi-astrology-business-prediction-real.webp",
    imageAlt: "Shopkeeper at his stall in Chickpet Bazaar, Bengaluru",
    date: "2026-08-09",
    readTime: "18 min read",
  },
  {
    slug: "nadi-astrology-father-prediction",
    category: "Father readings",
    title: "Nadi Astrology Father Prediction: Kandam 9 Guide",
    description:
      "What Kandam 9 may say about father, inheritance, mentors and spiritual duty—and how to protect consent, relationships, documents and elder care.",
    image: "/images/blog-nadi-astrology-father-prediction-real.webp",
    imageAlt: "Circa-1860 studio portrait of a father with five children in Delhi",
    date: "2026-08-09",
    readTime: "18 min read",
  },
  {
    slug: "nadi-astrology-8th-kandam",
    category: "Kandam 8",
    title: "Nadi Astrology 8th Kandam: Longevity Without Fear",
    description:
      "Understand traditional Kandam 8 longevity and accident claims, decide what you consent to hear, and respond without surrendering health, safety or peace of mind.",
    image: "/images/blog-nadi-astrology-8th-kandam-real.webp",
    imageAlt: "Four small glass hourglasses containing differently coloured sand",
    date: "2026-08-09",
    readTime: "18 min read",
  },
  {
    slug: "nadi-astrology-chennai",
    category: "Chennai guide",
    title: "Nadi Astrology Chennai: Choose a Centre and Plan Your Visit",
    description:
      "A practical Chennai guide to comparing Nadi centres, planning travel, protecting your information and understanding what location can—and cannot—prove.",
    image: "/images/blog-nadi-astrology-chennai-real.webp",
    imageAlt: "Full exterior view of Chennai Central railway station",
    date: "2026-08-09",
    readTime: "18 min read",
  },
  {
    slug: "nadi-astrology-leaf-not-found",
    category: "Leaf search",
    title: "Nadi Astrology Leaf Not Found: What Happens Next?",
    description:
      "Understand no-match outcomes, document the search, protect your thumbprint and decide whether another attempt adds anything.",
    image: "/images/blog-nadi-astrology-leaf-not-found-real.webp",
    imageAlt: "Wooden collection cabinets inside Raghunandan Library in Puri",
    date: "2026-08-09",
    readTime: "17 min read",
  },
  {
    slug: "nadi-astrology-reviews",
    category: "Reviews & trust",
    title: "Nadi Astrology Reviews: What to Trust Before Booking",
    description:
      "Learn which review details matter, how to detect duplication, and why service experience differs from proof of a prediction.",
    image: "/images/blog-nadi-astrology-reviews-real.webp",
    imageAlt: "Handwritten guest-book review held in front of a window",
    date: "2026-08-09",
    readTime: "17 min read",
  },
  {
    slug: "nadi-astrology-reading-cost",
    category: "Reading costs",
    title: "Nadi Astrology Reading Cost: A Transparent Price Guide",
    description:
      "Compare leaf search, matching, Kandams, translation, refunds and remedies without relying on unsupported market averages.",
    image: "/images/blog-nadi-astrology-reading-cost-real.webp",
    imageAlt: "Printed prepaid service receipt issued in Kollam, Kerala",
    date: "2026-08-09",
    readTime: "17 min read",
  },
  {
    slug: "nadi-astrology-sibling-prediction",
    category: "Sibling readings",
    title: "Nadi Astrology Sibling Prediction: Kandam 3 Guide",
    description:
      "What the siblings chapter may claim, how matching details differ from prediction, and how to protect consent, privacy and family relationships.",
    image: "/images/blog-nadi-astrology-sibling-prediction-real.webp",
    imageAlt: "Historic 1895 group portrait of the Maharaja of Mysore with his brothers and sisters",
    date: "2026-08-09",
    readTime: "17 min read",
  },
  {
    slug: "nadi-astrology-legal-case-prediction",
    category: "Legal-matter readings",
    title: "Nadi Astrology Legal Case Prediction: Kandam 6 Guide",
    description:
      "What the litigation chapter may claim, how legal stages differ, and how to protect deadlines, evidence, privacy and informed choices.",
    image: "/images/blog-nadi-astrology-legal-case-prediction-real.webp",
    imageAlt: "Red-brick towers of the Madras High Court building in Chennai",
    date: "2026-08-09",
    readTime: "17 min read",
  },
  {
    slug: "nadi-astrology-property-prediction",
    category: "Property readings",
    title: "Nadi Astrology Property Prediction: Kandam 4 Guide",
    description:
      "What the home and land chapter may claim, how adjacent Kandams differ, and which title, project, cost and consent checks still matter.",
    image: "/images/blog-nadi-astrology-property-prediction-real.webp",
    imageAlt: "A white house surrounded by palm trees in Uthandi, Chennai",
    date: "2026-08-09",
    readTime: "17 min read",
  },
  {
    slug: "nadi-astrology-education-prediction",
    category: "Education readings",
    title: "Nadi Astrology Education Prediction: Kandam 2 Guide",
    description:
      "What the education chapter may claim, how it connects to higher study, and how to choose a course using evidence as well as reflection.",
    image: "/images/blog-nadi-astrology-education-prediction-real.webp",
    imageAlt: "Reading hall inside Ibn-e-Sina Library at Jamia Millia Islamia in New Delhi",
    date: "2026-08-09",
    readTime: "17 min read",
  },
  {
    slug: "nadi-astrology-foreign-travel-prediction",
    category: "Travel readings",
    title: "Nadi Astrology Foreign Travel Prediction: Kandam 12",
    description:
      "What the foreign-travel chapter may mean, why a journey differs from visa approval, and how to plan overseas work, study or settlement safely.",
    image: "/images/blog-nadi-astrology-foreign-travel-prediction-real.webp",
    imageAlt: "Exterior of Chennai International Airport terminal",
    date: "2026-08-09",
    readTime: "17 min read",
  },
  {
    slug: "nadi-astrology-wealth-prediction",
    category: "Wealth readings",
    title: "Nadi Astrology Wealth Prediction: Kandams 2 and 11",
    description:
      "How the wealth and gains chapters differ, what a leaf may claim, and how to reflect without treating a spiritual forecast as investment advice.",
    image: "/images/blog-nadi-astrology-wealth-prediction-real.webp",
    imageAlt: "Modern Indian coins ranging from five paise to two rupees",
    date: "2026-08-09",
    readTime: "17 min read",
  },
  {
    slug: "nadi-astrology-health-prediction",
    category: "Health readings",
    title: "Nadi Astrology Health Prediction: Kandam 6 Explained",
    description:
      "What the health chapter may claim, how to translate it carefully, and how to respond without confusing a spiritual reading with diagnosis or treatment.",
    image: "/images/blog-nadi-astrology-health-prediction-real.webp",
    imageAlt: "A doctor attending patients at a free medical clinic in Mizoram, India",
    date: "2026-08-08",
    readTime: "17 min read",
  },
  {
    slug: "nadi-astrology-past-life-reading",
    category: "Past life & karma",
    title: "Nadi Astrology Past Life Reading: Kandam 13 Explained",
    description:
      "What the past-life chapter may claim, how to separate sacred narrative from verified memory, and how to choose present-life action without fear or blame.",
    image: "/images/blog-nadi-astrology-past-life-reading-real.webp",
    imageAlt: "A 16th-century Bhagavata Purana manuscript written on palm leaf",
    date: "2026-08-08",
    readTime: "17 min read",
  },
  {
    slug: "nadi-astrology-child-prediction",
    category: "Children & family",
    title: "Nadi Astrology Child Prediction: Kandam 5 Explained",
    description:
      "What the children chapter may reveal, how to interpret it carefully, and why fertility, pregnancy and child-health decisions require medical evidence.",
    image: "/images/blog-nadi-astrology-child-prediction-real.webp",
    imageAlt: "A family photographed together in Madhya Pradesh, India",
    date: "2026-08-08",
    readTime: "17 min read",
  },
  {
    slug: "nadi-astrology-career-prediction",
    category: "Career readings",
    title: "Nadi Astrology Career Prediction: Chapter 10 Explained",
    description:
      "What the profession chapter may reveal, how leaf readings differ from chart methods, and how to test career guidance without risking your livelihood.",
    image: "/images/blog-nadi-astrology-career-prediction-real.webp",
    imageAlt: "An Indian craftsperson finishing a metal utensil at Dilli Haat in New Delhi",
    date: "2026-08-08",
    readTime: "17 min read",
  },
  {
    slug: "nadi-astrology-marriage-prediction",
    category: "Marriage readings",
    title: "Nadi Astrology Marriage Prediction: A Decision-Safe Guide",
    description:
      "What Chapter 7 may reveal, how it differs from Nadi Dosha, and how to use marriage predictions without surrendering consent or judgment.",
    image: "/images/blog-nadi-astrology-marriage-prediction-real.webp",
    imageAlt: "A Tamil wedding ceremony in which a groom ties a thali around the bride's neck",
    date: "2026-08-08",
    readTime: "17 min read",
  },
  {
    slug: "bhrigu-nadi-astrology",
    category: "Sages & lineages",
    title: "Bhrigu Nadi Astrology: Leaf, Samhita or Chart Method?",
    description:
      "Separate Bhrigu palm-leaf readings, Bhrigu Samhita records and Bhrigu Nandi Nadi chart methods before choosing a consultation.",
    image: "/images/blog-bhrigu-nadi-astrology-real.webp",
    imageAlt: "An idol identified as Sage Bhrigu at Bhrugu Maharaj Mandir in Maharashtra",
    date: "2026-08-08",
    readTime: "17 min read",
  },
  {
    slug: "agastya-nadi-astrology",
    category: "Sages & lineages",
    title: "Agastya Nadi Astrology: Sage, Tradition and Reading Guide",
    description:
      "Who Sage Agastya is in tradition, what his name means in palm-leaf readings and how to separate sacred attribution, manuscript and modern service.",
    image: "/images/blog-agastya-nadi-astrology-real.webp",
    imageAlt: "A devotional representation of Sage Agastya photographed in Tamil Nadu",
    date: "2026-08-08",
    readTime: "17 min read",
  },
  {
    slug: "is-nadi-astrology-genuine",
    category: "Authentic Nadi experience",
    title: "Is Nadi Astrology Genuine? How Authentic Leaf Finding Works",
    description:
      "Explore the sacred palm-leaf tradition, thumb-impression matching, the index-leaf experience and NadiVedas’ live leaf-finding process.",
    image: "/images/blog-is-nadi-astrology-genuine-real.webp",
    imageAlt: "Displayed Ramayana palm-leaf manuscript with an ivory cover at a Chennai government manuscript library",
    date: "2026-08-08",
    readTime: "16 min read",
  },
  {
    slug: "how-to-prepare-for-nadi-astrology-reading",
    category: "Reading preparation",
    title: "How to Prepare for a Nadi Astrology Reading",
    description:
      "A practical before, during and after checklist for Nadi leaf matching: thumbprint, privacy, questions, costs, recording, interpretation and safe decisions.",
    image: "/images/blog-nadi-reading-preparation-real.webp",
    imageAlt: "Tamil palm-leaf manuscripts displayed at the Thirumalai Nayakkar Mahal Museum in Madurai",
    date: "2026-08-07",
    readTime: "17 min read",
  },
  {
    slug: "nadi-astrology-history",
    category: "History & manuscripts",
    title: "Nadi Astrology History: Tradition, Manuscripts and Evidence",
    description:
      "Trace Nadi astrology from sacred origin stories to surviving palm-leaf culture, recopying, archives and the evidence questions every seeker should ask.",
    image: "/images/blog-nadi-astrology-history-real.webp",
    imageAlt: "Historic multi-text palm-leaf manuscript preserved in a Chennai library",
    date: "2026-08-07",
    readTime: "18 min read",
  },
  {
    slug: "vaitheeswaran-koil-nadi-astrology",
    category: "Places & tradition",
    title: "Vaitheeswaran Koil Nadi Astrology: A Practical Guide",
    description:
      "Understand the temple town, its connection with palm-leaf readings, how to plan a visit, compare centres and keep worship separate from commercial claims.",
    image: "/images/blog-vaitheeswaran-koil-guide-real.webp",
    imageAlt: "Sculpted deities on a shrine inside Vaitheeswaran Koil temple",
    date: "2026-08-07",
    readTime: "17 min read",
  },
  {
    slug: "nadi-astrology-remedies",
    category: "Remedies & ethics",
    title: "Nadi Astrology Remedies: Meaning, Types and Safe Choices",
    description:
      "A grounded guide to Pariharam, Shanti and Deeksha remedies—what they mean in tradition, common forms, costs, consent and important safety boundaries.",
    image: "/images/blog-nadi-remedies-real.webp",
    imageAlt: "Rows of oil lamps glowing inside a Hindu temple",
    date: "2026-08-07",
    readTime: "17 min read",
  },
  {
    slug: "nadi-astrology-online-reading",
    category: "Online readings",
    title: "Nadi Astrology Online Reading: A Safe, Practical Guide",
    description:
      "How online palm-leaf matching works, what to prepare, how to assess a provider and which privacy, payment and recording questions to ask.",
    image: "/images/blog-nadi-online-reading-real.webp",
    imageAlt: "Woman using a laptop for a video call at home",
    date: "2026-08-07",
    readTime: "16 min read",
  },
  {
    slug: "nadi-astrology-kandams",
    category: "Reading chapters",
    title: "Nadi Astrology Kandams: The 16 Palm-Leaf Chapters Explained",
    description:
      "A clear guide to the 12 core and four special Kandams, why chapter lists differ, what each covers and how to choose without overspending.",
    image: "/images/blog-nadi-kandams-real.webp",
    imageAlt: "Real Tamil palm-leaf manuscript showing several inscribed folios",
    date: "2026-08-07",
    readTime: "17 min read",
  },
  {
    slug: "nadi-astrology-thumb-impression",
    category: "Leaf finding",
    title: "Nadi Astrology Thumb Impression: How the Palm-Leaf Search Works",
    description:
      "A practical, transparent guide to which thumb is used, traditional classification, print quality, bundle search, live matching, privacy and a confident reading experience.",
    image: "/images/blog-nadi-thumb-impression-real.webp",
    imageAlt: "Real scanned fingerprint showing a whorl ridge pattern",
    date: "2026-08-07",
    readTime: "16 min read",
  },
  {
    slug: "what-is-nadi-astrology-complete-guide",
    category: "Pillar guide",
    title: "What Is Nadi Astrology? The Complete Guide to Palm-Leaf Readings",
    description:
      "A detailed, transparent guide to the Nadi astrology tradition, thumb-impression search, live leaf matching, Kandams, lineages, online readings and what to expect.",
    image: "/images/blog-nadi-astrology-complete-guide.webp",
    imageAlt:
      "Traditional Nadi reader examining a palm-leaf manuscript in an ancient South Indian archive",
    date: "2026-08-07",
    readTime: "18 min read",
  },
] as const;
