export type JournalPost={slug:string;category:string;title:string;description:string;readTime:string;intro:string;sections:{heading:string;paragraphs:string[]}[];faq?:{question:string;answer:string}[]};

export const journalPosts:JournalPost[]=[
 {slug:"what-is-nadi-astrology",category:"Nadi foundations",title:"What Is Nadi Astrology—and How Is It Different?",description:"A clear introduction to the palm-leaf manuscript tradition, the matching process and what makes a Nadi reading distinct.",readTime:"7 min read",intro:"Nadi astrology is a South Indian palm-leaf manuscript tradition in which a seeker’s record is searched for, matched and then read. The experience begins with identity verification—not with a generic forecast.",sections:[
  {heading:"The index leaf before the continuation",paragraphs:["A Nadi consultation does not begin by assuming that a manuscript exists for every visitor. After the ₹999 booking and thumbprint upload, Guruji classifies the ridge pattern and searches likely candidate bundles.","On Google Meet, Guruji tests identifying leaves through statements answered yes or no. The matched index leaf is like the first or index page of a book: it identifies the seeker. The separate continuation bundle contains the future-prediction reading."]},
  {heading:"How it differs from a horoscope consultation",paragraphs:["A conventional astrology consultation commonly begins with a birth date, time and place and interprets a chart. In the Nadi process, those details are not used to manufacture the initial match. The manuscript must first identify the seeker through its own recorded details.","Once a leaf is matched, its chapters may address areas such as family, marriage, career, health, spiritual direction and remedies. The available depth depends on the lineage and the manuscript."]},
  {heading:"What a responsible experience should feel like",paragraphs:["The process should be transparent about what has and has not been found. Guruji should not force a match, and a seeker should not volunteer extra information during elimination. At NadiVedas, the ₹999 index-leaf finding fee is refunded if no index leaf is found.","A verified index leaf is an invitation to consider the separate continuation bundle, not an obligation. Continuation-bundle readings contain the future-prediction material, start from ₹11,800, vary by lineage and are paid only if you choose to continue."]}
 ],faq:[{question:"Is a Nadi leaf guaranteed to be found?",answer:"No. An authentic search can end without a match, which is why NadiVedas refunds the ₹999 leaf-finding fee when no leaf is found."},{question:"Do I need an exact birth time to begin?",answer:"No. The initial bundle search uses your thumb impression, gender and broad birth-year information."}]},
 {slug:"why-thumb-impression-matters",category:"Leaf finding",title:"Why Your Thumb Impression Matters",description:"How traditional ridge classifications narrow a vast palm-leaf library to the bundles most likely to contain your record.",readTime:"6 min read",intro:"Your thumb impression is the practical starting point of a Nadi leaf search. It helps the library narrow thousands of manuscripts into a small set of bundles that can be examined carefully.",sections:[
  {heading:"Classification, not fortune-telling",paragraphs:["The thumbprint is used as a library key. Traditional Nadi practice groups ridge patterns into classifications and sub-classifications so the search can move toward a relevant part of the archive.","Men traditionally submit the right thumb and women the left. A clean, well-lit image with the full print visible helps avoid delays or incorrect classification."]},
  {heading:"From a fingerprint to the index leaf",paragraphs:["After classification, Guruji searches likely candidate bundles. Each candidate index leaf must still be tested; the print does not by itself prove which record corresponds to you.","This is why the Google Meet matching call matters. Guruji reads identifying statements one by one, allowing unsuitable leaves to be eliminated. Once verified, the index leaf points to the separate continuation bundle used for the future-prediction reading."]},
  {heading:"How to submit a useful impression",paragraphs:["Use a dark ink impression on plain white paper when possible. Keep the image sharp, include the entire thumb pad, avoid glare and do not apply filters. If the ridges are unclear, the team may request another image.","The impression is collected only after the ₹999 leaf-finding booking. It is part of the search process, not a public profile or a prediction in itself."]}
 ],faq:[{question:"Which thumb should I provide?",answer:"Traditionally, men provide the right thumb and women provide the left thumb."},{question:"Does the thumbprint reveal my prediction?",answer:"No. It helps classify and locate likely manuscript bundles; the leaf must still be matched during a live call."}]},
 {slug:"13-nadi-kandams-explained",category:"Reading guide",title:"The 13 Nadi Kandams Explained",description:"A practical map of the life chapters commonly associated with identity, family, career, relationships, karma and remedies.",readTime:"8 min read",intro:"Nadi manuscripts are organised into Kandams, or chapters. Each chapter concentrates on a different area of life, allowing a reading to move from identity and family toward specific questions and remedies.",sections:[
  {heading:"The index leaf and general continuation chapter",paragraphs:["The index leaf establishes identity during the live match. Think of it as the first or index page of a book rather than the complete future-prediction reading.","After a successful match, the separate continuation bundle may begin with a general Kandam and move into available life-area chapters. Continuation-bundle readings start from ₹11,800."]},
  {heading:"Life-area chapters",paragraphs:["The second through twelfth chapters traditionally explore themes such as family and wealth, siblings, mother and home, children, health and obstacles, marriage, longevity, fortune, profession, gains and spiritual expenditure.","Not every seeker needs every chapter. A focused reading can be more useful when the question is clear, while an Ultra or family-oriented reading may bring several areas together in greater depth."]},
  {heading:"Remedies and past-life context",paragraphs:["The thirteenth chapter is commonly associated with past-life karma and prescribed remedies. Remedies should be explained clearly, without fear or pressure, and their spiritual meaning should be understood before action.","Available chapters and depth differ by lineage. The guided journey helps you consider the Nadi that best matches the kind of insight you are seeking."]}
 ],faq:[{question:"Must I purchase all 13 chapters?",answer:"No. The appropriate depth depends on your question, the lineage and the reading format you choose after a successful match."},{question:"Is matching the same as a full first-chapter reading?",answer:"No. Matching verifies your leaf; the full reading is a separate, optional step."}]},
 {slug:"shiva-nadi-vs-agastya-nadi",category:"Traditions",title:"Shiva Vakya Nadi vs Agastya Nadi",description:"Understand the character, scope and common use cases of two of the best-known Nadi lineages.",readTime:"6 min read",intro:"Shiva Vakya and Agastya are not simply two price points. They are distinct lineages with different voices, emphases and levels of depth. The better choice depends on what you are seeking.",sections:[
  {heading:"Shiva Vakya Nadi",paragraphs:["Shiva Vakya Nadi is presented through the sacred dialogue of Lord Shiva and Parvati. Seekers often choose it when they want an expansive view across relationships, career, finance, family karma, spirituality and major turning points.","Its character is direct and comprehensive, making it NadiVedas’ most frequently selected lineage for people who want broad life direction rather than one isolated answer."]},
  {heading:"Agastya Nadi",paragraphs:["Agastya Nadi is associated with Sage Agastya and offers a foundational, practical overview. It can be a strong entry point for career, marriage, family and financial guidance without beginning at the deepest reading tier.","A lower starting fee does not make the lineage less authentic. It indicates a different format and depth, which should be understood only after your leaf has been matched."]},
  {heading:"How to choose without guessing",paragraphs:["Start with the question you most want clarity about: a complete life direction, a major decision, relationships, health, prosperity or spiritual growth. The guided questionnaire uses that intention to suggest a lineage.","Index-leaf finding costs ₹999. After a verified match, the separate continuation-bundle reading contains the future-prediction material, starts from ₹11,800, varies by tradition and is paid only if you decide to proceed."]}
 ],faq:[{question:"Which lineage is most popular?",answer:"Shiva Vakya Nadi is currently the most frequently selected at NadiVedas."},{question:"Can the team help me choose?",answer:"Yes. The guided journey asks what you are seeking and recommends a lineage before the manuscript search."}]},
 {slug:"prepare-for-nadi-matching-session",category:"Preparation",title:"How to Prepare for a Live Nadi Matching Session",description:"Know what to bring, why yes-or-no answers matter and how to protect the integrity of the matching process.",readTime:"5 min read",intro:"A calm, disciplined matching call gives the manuscript the best opportunity to identify you. The most important preparation is surprisingly simple: listen carefully and answer only what is asked.",sections:[
  {heading:"Before the call",paragraphs:["Choose a quiet place, use a stable internet connection and keep enough uninterrupted time available. Have headphones ready if privacy matters and join from a device that allows you to hear the Guruji clearly.","Do not rehearse your biography or send unnecessary personal details. The initial leaf search relies on the thumb impression, gender and broad birth-year information already collected."]},
  {heading:"During elimination",paragraphs:["Answer each statement with yes or no. If a statement is wrong, the Guruji moves to another leaf. If it is right, the same leaf is tested further. Avoid explaining, correcting or adding clues unless the team specifically asks for clarification.","A strong match brings several identifiers together on one leaf—for example your name, parents’ names, marital or family status, and birth-related markers. One correct statement alone is never enough."]},
  {heading:"After the index leaf matches",paragraphs:["The team explains the related continuation-bundle format, likely duration, lineage and fee. You may ask questions and decide whether the future-prediction reading is right for you.","There is no obligation to continue. Continuation-bundle readings begin at ₹11,800 and are paid only after the index leaf is verified and you choose the next step."]}
 ],faq:[{question:"Should I share my family details before matching?",answer:"No. Avoid volunteering personal information; the leaf should establish the match through its own statements."},{question:"What if I cannot hear or understand a statement?",answer:"Ask for it to be repeated or translated rather than guessing."}]},
 {slug:"what-if-nadi-leaf-is-not-found",category:"Integrity",title:"What Happens When a Nadi Leaf Is Not Found?",description:"Why an honest no-match protects the integrity of the tradition—and how NadiVedas’ refund promise works.",readTime:"5 min read",intro:"A no-match is not a failure to be hidden. It is one possible and honest outcome of searching a finite manuscript archive, and it is better than forcing a leaf that does not identify you.",sections:[
  {heading:"Why a search can end without a match",paragraphs:["The likely bundles may not contain a leaf whose statements consistently match your identity. A print may also need clearer capture or the relevant manuscript may not be available in the searched library.","The Guruji should eliminate inconsistent leaves rather than stretch an answer. Multiple personal details must align within one manuscript before it is treated as your record."]},
  {heading:"The NadiVedas refund promise",paragraphs:["Your first payment is ₹999 for finding and verifying the index leaf. If no index leaf is found after Guruji's bundle search and Google Meet matching process, that fee is refunded under the stated policy.","If the index leaf is found, the team explains the separate continuation-bundle reading containing the future-prediction material. It starts at ₹11,800 and varies by lineage, but no such payment is required before the match."]},
  {heading:"What to do next",paragraphs:["A no-match does not make a judgement about your destiny. It only means that a verifiable manuscript was not found in that search. Do not allow anyone to turn uncertainty into fear or pressure.","Keep confirmation of the search outcome and follow the refund instructions provided by the support team. You may also review the published refund policy before booking."]}
 ],faq:[{question:"Is the ₹999 fee refundable if no leaf is found?",answer:"Yes. NadiVedas refunds the leaf-finding fee when no matching leaf is found."},{question:"Do I have to buy a full reading when a leaf is found?",answer:"No. Continuing is entirely optional."}]}
];

export const getJournalPost=(slug:string)=>journalPosts.find(post=>post.slug===slug);
