export const nadiPrices = [
  {
    id: "shiva",
    name: "Shiva Vakya Nadi",
    sage: "Lord Shiva & Parvati",
    price: "₹21,500",
    ultra: "₹50,500",
    image: "/images/shiva-clean.webp",
    tag: "Most Popular",
    focus:
      "Marriage, career, finance, spirituality, family karma, remedies and complete life direction.",
  },
  {
    id: "nandi",
    name: "Nandi Nadi",
    sage: "Nandi Deva",
    price: "₹24,500",
    ultra: "₹50,500",
    image: "/images/nandi-nadi.webp",
    tag: "Rare",
    focus:
      "Finance, business, career, spiritual growth, rare karmic clarity and remedies.",
  },
  {
    id: "kaka",
    name: "Kakabhushundi Nadi",
    sage: "Sage Kakabhushundi",
    price: "₹19,500",
    ultra: "₹46,000",
    image: "/images/kakabhushundi-clean.webp",
    tag: "Career",
    focus:
      "Career, finance, business timing, destiny patterns and major life decisions.",
  },
  {
    id: "vasishta",
    name: "Vashishta Nadi",
    sage: "Sage Vashishta & Sri Rama",
    price: "₹14,800",
    ultra: "₹30,800",
    image: "/images/vasishta-clean.webp",
    tag: "Dharma",
    focus:
      "Dharma, career, marriage, family, finance, practical direction and remedies.",
  },
  {
    id: "thirumoolar",
    name: "Thirumoolar Nadi",
    sage: "Siddhar Thirumoolar",
    price: "₹13,800",
    ultra: "₹36,800",
    image: "/images/thirumoolar-divine.webp",
    tag: "Spirituality",
    focus:
      "Spirituality, health, discipline, remedies and higher life purpose.",
  },
  {
    id: "bhogar",
    name: "Bhogar Nadi",
    sage: "Siddhar Bhogar",
    price: "₹12,800",
    ultra: "₹36,800",
    image: "/images/bhogar-divine.webp",
    tag: "Healing",
    focus:
      "Health, wellness, remedies, healing karma and spiritual protection.",
  },
  {
    id: "dhanvantari",
    name: "Dhanvantari Nadi",
    sage: "Lord Dhanvantari",
    price: "₹22,500",
    ultra: "₹50,500",
    image: "/images/dhanvantari-nadi.webp",
    tag: "Health",
    focus:
      "Health patterns, wellness, healing remedies and spiritual protection.",
  },
  {
    id: "shukra",
    name: "Shukra Nadi",
    sage: "Shukracharya",
    price: "₹22,500",
    ultra: "₹50,500",
    image: "/images/shukra-nadi.webp",
    tag: "Prosperity",
    focus: "Marriage, love, wealth, property, income, comforts and prosperity.",
  },
  {
    id: "bhrigu",
    name: "Bhrighu Nadi",
    sage: "Sage Bhrighu",
    price: "₹17,500",
    ultra: "₹38,800",
    image: "/images/bhrigu-clean.webp",
    tag: "Destiny",
    focus:
      "Career, finance, marriage, life timing, major decisions and remedies.",
  },
  {
    id: "atri",
    name: "Atri Nadi",
    sage: "Sage Atri & Dattatreya",
    price: "₹18,500",
    ultra: "₹46,800",
    image: "/images/atri-clean.webp",
    tag: "Blessings",
    focus:
      "Health, spiritual protection, family karma, remedies and blessings.",
  },
  {
    id: "agastya",
    name: "Agastya Nadi",
    sage: "Sage Agastya",
    price: "₹11,800",
    ultra: "₹26,500",
    image: "/images/agastya-divine.webp",
    tag: "Foundational",
    focus:
      "Career, marriage, family, finance, foundational guidance and predictions.",
  },
  {
    id: "brahma",
    name: "Brahma Nadi",
    sage: "Lord Brahma",
    price: "₹26,500",
    ultra: "₹67,000",
    image: "/images/brahma-nadi.webp",
    tag: "Rare Ultra",
    focus:
      "Deep destiny mapping, life purpose, spiritual direction and karmic design.",
  },
];

export const chapters = [
  "General Life",
  "Wealth & Family",
  "Siblings & Courage",
  "Mother & Happiness",
  "Children & Intelligence",
  "Health & Obstacles",
  "Marriage & Partnership",
  "Longevity & Transformation",
  "Fortune & Dharma",
  "Career & Authority",
  "Gains & Aspirations",
  "Liberation & Expenditure",
  "Remedies & Past-Life Karma",
];
