import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { SiteHeader, SiteFooter } from "./SiteChrome";
import { cityBlogArticles, type CityBlogArticle as Article } from "../lib/city-blog-articles";

const traditions = [
  ["Shiva Nadi", "/shiva-nadi", "Shaiva guidance, karma, duty and spiritual practice"],
  ["Shiva Vakya Nadi", "/blogs/shiva-vakya-nadi-astrology", "a Shiva–Parvati dialogue attribution used by some collections"],
  ["Agastya Nadi", "/blogs/agastya-nadi-astrology", "the best-known sage attribution in Tamil palm-leaf practice"],
  ["Nandi Nadi", "/blogs/nandi-nadi-astrology", "stewardship, disciplined responsibility and Shaiva devotion"],
  ["Brahma Nadi", "/blogs/brahma-nadi-astrology", "creation, life purpose and destiny themes"],
  ["Atri Nadi", "/blogs/atri-nadi-astrology", "family lineage, care, learning and spiritual discipline"],
  ["Bhogar Nadi", "/blogs/bhogar-nadi-astrology", "a Siddha and Palani-associated attribution"],
  ["Bhrigu Nadi", "/blogs/bhrigu-nadi-astrology", "a name that may refer to palm leaves, a Samhita or chart methods"],
  ["Thirumoolar Nadi", "/blogs/thirumoolar-nadi-astrology", "a Siddha and Tirumantiram-associated tradition"],
  ["Dhanvantari Nadi", "/blogs/dhanvantari-nadi-astrology", "health-centred spiritual reflection with strict medical boundaries"],
  ["Shukra Nadi", "/blogs/shukra-nadi-astrology", "relationships, values, creativity and prosperity"],
  ["Kakabhushundi Nadi", "/blogs/kakabhushundi-nadi-astrology", "long cycles, recurring patterns and Rama devotion"],
  ["Vasishtha Nadi", "/vasishtha-nadi", "a sage-lineage attribution that should be verified collection by collection"],
] as const;

export function cityMetadata(a: Article): Metadata {
  const url = `https://www.nadivedas.com/blogs/${a.slug}`;
  return { title:a.title, description:a.description, alternates:{canonical:url}, openGraph:{type:"article",url,title:a.title,description:a.description,publishedTime:"2026-08-15T21:30:00+05:30",modifiedTime:"2026-08-15T21:30:00+05:30",authors:["NadiVedas Editorial Team"],images:[{url:`https://www.nadivedas.com${a.image}`,width:a.imageWidth,height:a.imageHeight,alt:a.imageAlt}]}, twitter:{card:"summary_large_image",title:a.title,description:a.description,images:[`https://www.nadivedas.com${a.image}`]} };
}

export function CityBlogArticle({article:a}:{article:Article}) {
  const url=`https://www.nadivedas.com/blogs/${a.slug}`;
  const faqs:Array<[string,string]>=[
    [`Is Nadi astrology available in ${a.city}?`,`Yes. ${a.city} seekers can explore local practitioners or join NadiVedas remotely. With NadiVedas, Guruji performs the leaf search and verifies the index-leaf matching live, allowing the seeker to participate from ${a.city} without travelling first.`],
    [`Can I book Shiva Nadi astrology in ${a.city}?`,`A provider may advertise Shiva Nadi or Shiva Vakya Nadi in ${a.city}, but names are used differently across centres. Confirm whether the service is a thumb-impression palm-leaf search, a chart reading or a general spiritual consultation.`],
    [`Is Dhanvantari Nadi available in ${a.city}?`,`Some services offer Dhanvantari-labelled health readings online or locally. Treat them as spiritual reflection only. They cannot diagnose illness, choose medicine or replace qualified healthcare.`],
    [`Which language can I use for a ${a.city} Nadi reading?`,`Commonly requested languages include ${a.languages.join(", ")}. Ask whether translation is live, who translates and whether you can hear or record the original source wording.`],
    ["Which thumb impression is used?","Many centres traditionally request the right thumb for men and left thumb for women, but practices vary and gender-diverse seekers should ask how the centre classifies prints. The print is biometric data, so confirm access, retention and deletion first."],
    ["What if no palm leaf matches?","No match should remain a valid outcome. Ask what bundles were searched and whether the ₹999 search fee is refundable or non-refundable before paying. Do not change accurate answers merely to force acceptance."],
    ["Are remedies included in the ₹999 search?","The ₹999 service covers Guruji's index-leaf search and live verification. After a match, the continuation reading reveals the guidance available in the bundle, including any traditional remedies. The team explains the next step and its price clearly so you can choose the guidance that feels right for you."],
  ];
  const graph={"@context":"https://schema.org","@graph":[{"@type":"Article",headline:a.title,description:a.description,image:`https://www.nadivedas.com${a.image}`,datePublished:"2026-08-15",dateModified:"2026-08-15",author:{"@type":"Organization",name:"NadiVedas Editorial Team",url:"https://www.nadivedas.com/about"},publisher:{"@type":"Organization",name:"NadiVedas",logo:{"@type":"ImageObject",url:"https://www.nadivedas.com/images/nadivedas-logo-full.png"}},mainEntityOfPage:url,about:[`Nadi astrology in ${a.city}`,"Shiva Nadi","Palm-leaf reading","Thumb-impression matching"],spatialCoverage:{"@type":"City",name:a.city,containedInPlace:{"@type":"AdministrativeArea",name:a.state}}},{"@type":"FAQPage",mainEntity:faqs.map(([q,text])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text}}))}]};
  return <main className="new-site long-blog"><SiteHeader/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(graph)}}/>
    <header className="long-blog-hero"><Image src={a.image} alt={a.imageAlt} fill priority unoptimized sizes="100vw"/><div/><section><Link href="/blogs">← All blogs</Link><span>{a.category} · 18 min read</span><h1>{a.title}</h1><p>Find a transparent palm-leaf process from {a.city}—with local planning, lineage choices, language questions and privacy checks before you share a thumb impression.</p><footer><b>NadiVedas Editorial Team</b><time dateTime="2026-08-15">Published 15 August 2026</time><small>Reviewed for local accuracy, tradition boundaries and seeker safety</small></footer></section></header>
    <div className="long-blog-shell"><aside><b>In this guide</b><a href="#answer">Direct answer</a><a href="#local">{a.city} context</a><a href="#process">Reading process</a><a href="#traditions">Nadi traditions</a><a href="#areas">Areas served</a><a href="#verify">Verification</a><a href="#faq">FAQs</a><Link href="/journey">Begin ₹999 leaf finding →</Link></aside>
      <article className="long-blog-copy">
        <p className="blog-dek">A search for “Nadi astrology in {a.city}” usually begins with a local need: speak in a familiar language, avoid an unnecessary journey and understand who will handle a sensitive thumb impression. The city name can make a service easier to reach. It cannot establish that a palm leaf is authentic, personally matched or accurately translated.</p>
        <p>{a.city} search results often mix three different things: a reader physically based in the city, an online coordinator connecting to manuscripts elsewhere, and ordinary horoscope astrology marketed with the word Nadi. This guide gives you a method for telling them apart while preserving the spiritual meaning that draws many seekers to the tradition.</p>
        <div id="answer" className="blog-summary"><b>The direct answer</b><p>Nadi astrology is available to seekers in {a.city} through local appointments and online readings. A typical palm-leaf service asks for a thumb impression, classifies its ridge pattern, searches candidate bundles and tests identifying statements before interpreting a match. Ask where the manuscripts are physically kept, who reads and translates them, what happens when no leaf matches and how your biometric image is deleted. A {a.city} address is useful for access; it is not proof of lineage, antiquity or predictive accuracy.</p></div>
        <section id="local"><span>01</span><h2>What “Nadi astrology in {a.city}” should mean</h2>{a.localContext.map(p=><p key={p}>{p}</p>)}<p>{a.arrival}</p><figure className="blog-real-figure"><Image src={a.image} alt={a.imageAlt} width={a.imageWidth} height={a.imageHeight} unoptimized/><figcaption><b>{a.landmark} is shown to provide honest {a.city} context; it does not depict a Nadi centre or prove a manuscript claim.</b> <a href={a.attributionUrl} rel="noreferrer">{a.attributionLabel}</a>, licensed <a href={a.licenseUrl} rel="noreferrer">{a.licenseLabel}</a>. Resized and compressed to WebP; no scene elements added.</figcaption></figure></section>
        <section id="process"><span>02</span><h2>How a palm-leaf search works from {a.city}</h2><p>Begin by asking whether the appointment is a genuine candidate-leaf search. A coordinator may request a clear ink print or close photograph of the thumb, classify the ridge pattern and choose one or more bundles. During a live session, the reader voices short identifying statements. You answer only yes or no until a candidate is rejected, accepted or the available search ends.</p><p>Matching is not the same as prediction. Names, family order, marital status, occupation or broad life facts are used to test a candidate; only after acceptance should later chapters or interpretations begin. Keep a written tally of statements and avoid volunteering a biography. A fair process can end with “no match.”</p><p>Ask to see the physical leaf and hear the source wording where possible. Clarify whether it is in Tamil, another language or a later copy. Separate four layers in your notes: manuscript wording, oral reading, translation and practitioner commentary. A smooth English, Hindi, {a.languages[0]} or other explanation may hide uncertainty unless these layers remain visible.</p><div className="blog-checklist"><h3>Before sending the thumb impression</h3><p>✓ Confirm the search-only price and non-match terms.<br/>✓ Ask where the manuscript bundles are held.<br/>✓ Ask who can download or forward the thumb image.<br/>✓ Obtain a deletion period in writing.<br/>✓ Confirm the live reading and translation languages.<br/>✓ Request permission to record the session.<br/>✓ Keep remedies and continuation chapters optional.</p></div></section>
        <section id="traditions"><span>03</span><h2>Shiva Nadi and other Nadi traditions for {a.city} seekers</h2><p>A {a.city} seeker may be offered Shiva Nadi, Shiva Vakya Nadi, Dhanvantari Nadi or another named lineage. These names describe sacred attributions or collection categories; they do not guarantee that every centre has a separately catalogued manuscript family. Ask what the name identifies in that provider's actual practice.</p><p>Use the guide below to form a precise question rather than treating every lineage as interchangeable:</p><ul>{traditions.map(([name,href,note])=><li key={name}><Link href={href}><b>{name} in {a.city}</b></Link>: {note}.</li>)}</ul><p>The best choice is not necessarily the grandest name. Begin with your question, then ask what collection the reader can actually search. If a provider changes the lineage label after hearing your concerns, request a clear explanation. A personal leaf should lead the interpretation; a broad service category should not force your story into a fixed profile.</p><p>NadiVedas provides access to Shiva-related leaf finding for seekers in {a.city}. NadiVedas is the reading platform, while Shiva Nadi and Shiva Vakya Nadi are tradition names. Keeping the platform, sacred lineage and physical manuscript distinct helps every seeker understand exactly what is being offered.</p></section>
        <section id="areas"><span>04</span><h2>Nadi astrology across {a.city} neighbourhoods</h2><p>Seekers may look for Nadi astrology in {a.localities.slice(0,4).join(", ")} and nearby areas such as {a.localities.slice(4).join(", ")}. These locality names help with travel and language planning. They should not be used to create the impression that a separate manuscript archive exists in every neighbourhood.</p><p>If you book locally, verify the complete address, accessibility, reader's name and the service included. Ask whether a waiting area is private, whether family members can attend, and how long candidate matching may take. If the provider serves all these areas online, the page should say so plainly rather than implying a physical branch in each locality.</p><p>For an online reading from {a.city}, the meaningful location is where the leaf and reader are, not the seeker's neighbourhood. Ask for a live view of the bundle, a stable video connection, the reader's role and the translator's role. Avoid unknown apps that demand unnecessary contacts, files or device permissions.</p></section>
        <section><span>05</span><h2>Language, translation and recording</h2><p>Readers serving {a.city} may offer {a.languages.join(", ")}. “Available in a language” can mean direct reading, simultaneous interpretation or a summary produced later. Ask which applies. A direct source-language phrase followed by translation is easier to review than a long paraphrase with no visible boundary.</p><p>Names and technical terms may be approximate. Ask the translator to preserve alternatives instead of choosing the version that sounds most personal. Conditions such as “if,” “during,” “after” and “may” should not disappear. Record the session with consent and keep the original file, not only an edited highlight supplied after the reading.</p><p>Afterward, sort statements into prior facts, current descriptions, future claims and spiritual counsel. Verify prior facts against records while remembering what information you disclosed before matching. Give future claims a date and observable criterion. Spiritual guidance can be meaningful without being presented as measurable proof.</p></section>
        <section id="verify"><span>06</span><h2>How to compare a {a.city} Nadi provider</h2><p>Visibility in search results is not the same as authenticity. Compare the clarity of the process: Does the page name the reader and translator? Does it distinguish palm-leaf matching from birth-chart astrology? Does it state the search fee, no-match policy, privacy practice and optional later costs? Does it allow you to question a mismatch?</p><p>Do not treat testimonials as controlled evidence, and never accept an unverifiable number of clients, years or generations merely because it is repeated across copied pages. Ask for observable features of your own session. A trustworthy provider can explain uncertainty without turning doubt into a spiritual fault.</p><p>Check high-stakes claims outside astrology. Doctors assess symptoms and treatment; lawyers interpret law and deadlines; regulated advisers assess investments; official agencies decide visas, admissions and benefits. A leaf should not be used to stop medicine, accuse another person, borrow for a ritual, sign a contract or ignore a safety concern.</p><div className="blog-checklist"><h3>A five-minute comparison</h3><p>✓ Method: leaf search, chart reading or something else?<br/>✓ Source: where are the leaves and in what script?<br/>✓ People: who reads, translates and stores the print?<br/>✓ Price: search, chapters and remedies listed separately?<br/>✓ Outcome: can the process honestly end without a match?<br/>✓ Evidence: can you record and review exact statements?</p></div></section>
        <section><span>07</span><h2>Continuation guidance and traditional remedies</h2><p>NadiVedas begins with a clearly defined ₹999 index-leaf search and live verification. When a candidate leaf matches, Guruji can explain the continuation bundle and the life areas available for deeper guidance.</p><p>Traditional remedies may include prayer, mantra, charity, temple worship, fasting or ritual. Their purpose is to help the seeker respond to the leaf with devotion, discipline and constructive action. The wording, duration and complete cost are explained before you choose.</p><p>Take time to absorb the reading, revisit your notes and select the continuation chapters that matter most to your journey. This staged experience allows trust to grow naturally from the live match into deeper Nadi guidance.</p></section>
        <section id="faq"><span>08</span><h2>Frequently asked questions</h2>{faqs.map(([q,text])=><details key={q}><summary>{q}</summary><p>{text}</p></details>)}</section>
        <section><span>09</span><h2>Continue through the India city cluster</h2><p>Compare the process, language and travel questions in other city guides. These links describe access for local seekers; they do not claim that NadiVedas maintains a physical manuscript archive in every city.</p><ul>{cityBlogArticles.filter(city=>city.slug!==a.slug).map(city=><li key={city.slug}><Link href={`/blogs/${city.slug}`}>Nadi astrology in {city.city}</Link></li>)}</ul></section>
        <section className="blog-sources"><span>Sources and related guides</span><h2>Continue with process, history and evidence</h2><p>This guide uses the photographed landmark only for local context and does not infer astrological claims from it. For the tradition itself, continue with NadiVedas' documented process and safety guides.</p><ul><li><a href={a.attributionUrl} rel="noreferrer">Wikimedia Commons image record and licence</a></li><li><Link href="/blogs/what-is-nadi-astrology-complete-guide">What is Nadi astrology?</Link></li><li><Link href="/blogs/nadi-astrology-thumb-impression">Thumb-impression matching guide</Link></li><li><Link href="/blogs/is-nadi-astrology-genuine">Evidence, belief and authenticity</Link></li><li><Link href="/blogs/nadi-astrology-online-reading">Online Nadi reading guide</Link></li><li><Link href="/blogs/nadi-astrology-reading-cost">Transparent Nadi reading costs</Link></li></ul></section>
        <div className="article-next"><h2>Search for your leaf from {a.city}</h2><p>₹999 covers Guruji's index-leaf search and live verification. A match is not guaranteed. If a leaf matches, every continuation reading remains optional.</p><Link className="lux-btn" href="/journey">Begin leaf finding for ₹999</Link></div>
      </article>
    </div><SiteFooter/></main>;
}
