import type {Metadata} from "next";
import Link from "next/link";
import {LineagePage} from "../lib/lineage-pages";
import {SiteHeader,SiteFooter} from "./SiteChrome";
import {VideoTestimonials} from "./VideoTestimonials";
import {LineageVideo} from "./LineageVideo";
import {LocalizedPrice} from "./LocalizedPrice";
import "../lineage-landing.css";

export function lineageMetadata(page:LineagePage):Metadata{return {title:`${page.name} Reading & Palm Leaf Search | NadiVedas`,description:`Explore ${page.name}, its traditional focus, leaf-finding process and reading choices. Begin with a ₹${page.leafFee} refundable index-leaf search.`,alternates:{canonical:`/${page.slug}`},openGraph:{title:`${page.name} — Palm Leaf Search`,description:page.promise,url:`https://www.nadivedas.com/${page.slug}`,images:[page.image]}}}

const process=[["01","Reserve your search","Begin with the lineage-specific index-leaf finding fee."],["02","Share your thumb impression","Men generally provide the right thumb; women generally provide the left."],["03","Narrow the library","The traditional thumb category helps Guruji identify likely bundles."],["04","Verify live","Guruji reads identifying statements; you answer only yes or no."],["05","Recognise one match","A sequence of identity and close-family details must align on one leaf."],["06","Choose freely","Only after a match do you decide whether to hear the continuation reading."]];

export function LineageLanding({page}:{page:LineagePage}){const journey=`/journey/${page.slug}`;return <main className="new-site lineage-lp" style={{"--lineage-accent":page.accent} as React.CSSProperties}><SiteHeader showBooking={false}/>
  <section className="lp-hero"><img src={page.image} alt={`${page.name} sacred artwork associated with ${page.sage}`} fetchPriority="high"/><div className="lp-hero-shade"/><div className="lp-hero-copy"><span>{page.name} · {page.epithet}</span><h1>{page.hero}</h1><p>{page.promise}</p><div><Link href={journey}>Begin {page.name} leaf search · <LocalizedPrice inr={page.leafFee} kind="leaf" nadiId={page.id}/></Link><a href="#lineage">Discover the lineage ↓</a></div><small>Index-leaf finding only · Refunded if no matching leaf is found · Full reading is separate and optional</small></div></section>
  <section className="lp-proof"><div><b><LocalizedPrice inr={page.leafFee} kind="leaf" nadiId={page.id}/></b><span>refundable search</span></div><i/><div><b>Live</b><span>yes-or-no verification</span></div><i/><div><b>Choice</b><span>continue only after a match</span></div></section>
  <section className="lp-intro" id="lineage"><div><span>The lineage character</span><h2>{page.sage}<br/><em>and the wisdom carried forward.</em></h2><p>{page.introduction}</p><p>{page.tradition}</p></div><figure><img src={page.secondaryImage} alt={`${page.name} lineage visual`} loading="lazy"/><figcaption>{page.name} · traditional sacred-art interpretation</figcaption></figure></section>
  <section className="lp-themes"><header><span>What makes it distinct</span><h2>Not a different promise.<br/><em>A different voice of guidance.</em></h2><p>{page.speciality}</p></header><div>{page.themes.map(([title,text],i)=><article key={title}><b>{String(i+1).padStart(2,"0")}</b><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="lp-watch"><div><span>Watch before you decide</span><h2>Meet {page.name}<br/>in the NadiVedas tradition.</h2><p>The video is held behind a lightweight play cover so the page stays fast on mobile and does not load YouTube until you choose to watch.</p></div><LineageVideo videoId={page.videoId} title={page.videoTitle||`${page.name} introduction`} image={page.image}/></section>
  <section className="lp-fit"><div><span>Who may feel drawn to it</span><h2>Choose this lineage when…</h2>{page.suited.map(item=><p key={item}><b>✦</b>{item}</p>)}</div><aside><small>{page.name} at a glance</small>{page.distinctions.map(item=><strong key={item}>{item}</strong>)}<Link href={journey}>This lineage resonates with me →</Link></aside></section>
  <section className="lp-process"><header><span>The leaf-finding path</span><h2>Your name is not searched.<br/><em>Your thumbprint begins the trail.</em></h2></header><div>{process.map(([n,t,p])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{p}</p></article>)}</div></section>
  <section className="lp-pricing"><header><span>Two transparent decisions</span><h2>Search first.<br/><em>Choose depth only after a match.</em></h2></header><div><article className="start"><small>Step 1 · Begin here</small><h3>Index-leaf finding</h3><strong><LocalizedPrice inr={page.leafFee} kind="leaf" nadiId={page.id}/></strong><p>Thumb classification, candidate-bundle search and live verification.</p><b>Refunded if no matching index leaf is found</b><Link href={journey}>Begin the search →</Link></article><article><small>After a match · Optional</small><h3>Standard Reading</h3><strong><LocalizedPrice inr={page.standard}/></strong><p>Approximately one hour of detailed guidance centred on the seeker and the principal life themes present.</p><b>Paid only after a match</b></article><article className="ultra"><small>Deeper format · Optional</small><h3>Ultra Family Reading</h3><strong><LocalizedPrice inr={page.ultra}/></strong><p>Up to two hours of deeper interpretation that may extend into spouse, children and family patterns when present.</p><b>You + family depth · after a match</b></article></div></section>
  <VideoTestimonials/>
  <section className="lp-faq"><header><span>Before you begin</span><h2>Clear answers,<br/>without pressure.</h2></header><div><details open><summary>Is a {page.name} leaf guaranteed?<b>+</b></summary><p>No. The first payment covers a real search and live index-leaf verification. If no matching index leaf is found, the leaf-finding fee is refunded under the published policy.</p></details><details><summary>What does <LocalizedPrice inr={page.leafFee} kind="leaf" nadiId={page.id}/> include?<b>+</b></summary><p>It includes thumb-impression classification, the search through likely candidate bundles and the live yes-or-no verification. It does not include the continuation reading.</p></details><details><summary>When do I pay for the full reading?<b>+</b></summary><p>Only after one index leaf matches and you choose to continue. The Standard reading is <LocalizedPrice inr={page.standard}/>; Ultra is <LocalizedPrice inr={page.ultra}/>. Both are optional.</p></details><details><summary>Can this be completed online?<b>+</b></summary><p>Yes. Registration, payment, thumbprint guidance, booking and live verification can be completed remotely.</p></details></div></section>
  <section className="lp-final"><span>The leaf cannot be promised</span><h2>But the search can begin.</h2><p>Your {page.name} selection is carried directly into the booking, payment and CRM record. You will not be asked to choose the lineage again.</p><Link href={journey}>Begin {page.name} leaf finding · <LocalizedPrice inr={page.leafFee} kind="leaf" nadiId={page.id}/></Link><small>Full reading is separate and optional. No match means the search fee is refunded.</small></section>
  <p className="lp-note">Lineage note: sacred associations and origin accounts on this page reflect Nadi and devotional tradition. They are not presented as independently verified historical or scientific facts.</p><SiteFooter showSticky={false}/><div className="lp-sticky"><Link href={journey}>Begin {page.name} search · <LocalizedPrice inr={page.leafFee} kind="leaf" nadiId={page.id}/> →</Link></div>
  </main>}
