import type {Metadata} from "next";
import Link from "next/link";
import {SiteHeader,SiteFooter} from "../components/SiteChrome";
import {VideoTestimonials} from "../components/VideoTestimonials";
import {BrahmaVideo} from "./BrahmaVideo";
import "./brahma.css";
import "./direct-images.css";

export const metadata:Metadata={title:"Brahma Nadi Reading | Rare Palm Leaf Search | NadiVedas",description:"Explore the Brahma Nadi tradition, Saptarishi lineage story, rare matching process, 16 age-sequenced themes and ₹1,500 refundable leaf-finding step.",alternates:{canonical:"/brahma-nadi"},openGraph:{title:"Brahma Nadi — The Rarest Palm Leaf Search",description:"Discover the traditional Brahma Nadi lineage and begin a ₹1,500 palm-leaf search.",url:"https://www.nadivedas.com/brahma-nadi",images:["/images/brahma-nadi-saptarishis.webp"]}};
const chapters=["Life pattern","Wealth & family","Courage & siblings","Mother & home","Children & intellect","Health & obstacles","Marriage & partnership","Longevity & transformation","Fortune & dharma","Career & authority","Gains & fulfilment","Spirituality & release","Past karma & remedies","Political life (if applicable)","Enterprise & wealth creation (if applicable)","Higher spirituality & liberation"];
const faqs=[["What is Brahma Nadi?","Practising Nadi lineages describe Brahma Nadi as a rare palm-leaf tradition concerned with a seeker's broad life pattern, duties, relationships, prosperity, karma and spiritual purpose."],["Is its origin story historically proven?","No. Its association with Lord Brahma, the Saptarishis and Brahmarshi Vishwamitra belongs to lineage tradition and oral accounts. We present it as traditional belief, not independently verified history."],["Why is the leaf difficult to find?","The collection is described as limited and its matching requires specialist readers. NadiVedas currently assigns Brahma Nadi searches only to three eligible Gurujis."],["Is finding a leaf guaranteed?","No. Based on current NadiVedas operational experience, fewer than one in five Brahma Nadi searches may result in a match. Individual outcomes vary."],["What does ₹1,500 cover?","Thumb-impression classification, candidate-bundle search and live index-leaf verification. It does not include the full prediction reading."],["When is the full reading paid?","Only after an index leaf is found, identifying details match and you choose to continue. Standard is ₹26,500 and Ultra is ₹67,000."],["What if no leaf is found?","The ₹1,500 leaf-finding fee is refunded when no matching index leaf is found, subject to the published refund policy."],["Can it be read online?","Yes. Thumb-impression guidance, matching and live verification can be completed remotely."]];
export default function Page(){return <main className="new-site brahma-page"><SiteHeader showBooking={false}/>
<section className="brahma-hero"><img className="brahma-direct-image" src="/images/brahma-nadi-saptarishis.webp" alt="Sacred-art illustration of Lord Brahma, palm-leaf manuscripts and the Saptarishis" fetchPriority="high"/><div className="brahma-veil"/><div className="brahma-hero-copy"><span className="brahma-kicker">Brahma Nadi · A rare sacred lineage</span><h1>What if the rarest leaf<br/><em>carried your destiny?</em></h1><p>Brahma Nadi is sought by people who want more than one answer—a deeper view of destiny, family, duty, prosperity, karma and spiritual purpose.</p><div className="brahma-actions"><Link className="brahma-primary" href="/journey/brahma-nadi">Begin the leaf search · ₹1,500</Link><a href="#story">Discover the lineage ↓</a></div><small>Leaf finding only · Refunded if no matching index leaf is found · Full reading is separate and optional</small></div><div className="brahma-rarity"><b>&lt;20%</b><span>present observed<br/>match rate*</span></div></section>
<section className="brahma-trust"><div><b>3</b><span>eligible Gurujis</span></div><i/><div><b>16</b><span>age-sequenced themes</span></div><i/><div><b>₹1,500</b><span>refundable search</span></div><i/><div><b>Choice</b><span>continue after a match</span></div></section>
<section className="brahma-story" id="story"><div className="brahma-story-lead"><span className="brahma-kicker dark">The lineage account</span><h2>From cosmic intelligence<br/>to the wisdom of sages.</h2><p>Within Nadi tradition, Brahma represents creative intelligence—the ordering principle behind life. The tradition places the Trimurti at the highest layer of sacred consciousness, followed by enlightened rishis and the Siddhar lineages of Tamil culture.</p></div><div className="brahma-layers"><article><b>01</b><h3>Trimurti</h3><p>Shiva, Vishnu and Brahma are revered as the highest divine principles associated with distinct streams of sacred wisdom.</p></article><article><b>02</b><h3>Saptarishis</h3><p>The seven great sages are traditionally described as Brahma's Manasa Putras—mind-born sons entrusted with transmitting wisdom.</p></article><article><b>03</b><h3>Brahmarshi Vishwamitra</h3><p>Lineage accounts connect Brahma Nadi with Vishwamitra, honoured as a Brahmarshi, and later sages who preserved its teachings.</p></article><article><b>04</b><h3>Tamil palm-leaf tradition</h3><p>The teachings are said to have passed through generations of manuscript custodians and Nadi readers in Tamil Nadu.</p></article></div></section>
<section className="brahma-lineage-visual"><figure><img className="brahma-direct-image" src="/images/brahma-vishwamitra-lineage.webp" alt="Traditional transmission of Brahma Nadi wisdom through Vishwamitra and the Saptarishis" loading="lazy"/></figure><div><span className="brahma-kicker dark">Why the name Brahma Nadi?</span><h2>A wisdom stream associated with creation itself.</h2><p>Traditional readers describe this Nadi as a stream of knowledge associated with Brahma’s creative intelligence and carried through enlightened sages. Brahmarshi Vishwamitra is prominent in this account: a rishi whose title itself signifies attainment of Brahmarshi status.</p></div></section>
<section className="brahma-video"><div className="brahma-video-intro"><span className="brahma-kicker">Watch before you decide</span><h2>Understand Brahma Nadi in the words of our lineage.</h2><p>See why it is considered rare, how its search differs and what a seeker should expect. The video loads only when you choose to play it, keeping this page fast.</p></div><BrahmaVideo/></section>
<section className="brahma-process"><header><span className="brahma-kicker dark">The sacred search</span><h2>Your name is not searched.<br/><em>Your thumbprint begins the trail.</em></h2></header><div className="brahma-process-grid">{[["01","Reserve the search","Pay ₹1,500 for the Brahma Nadi index-leaf search."],["02","Share your thumb impression","Guruji classifies the traditional fingerprint pattern."],["03","Search candidate bundles","The library is narrowed to bundles associated with that category."],["04","Verify live with yes or no","Incorrect leaves are eliminated through identifying statements."],["05","Recognise a complete match","Identity and close-family details must align on one leaf."],["06","Choose whether to continue","Only after a match do you decide about a full reading."]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section className="brahma-discovery"><div><span className="brahma-kicker">The moment of verification</span><h2>Fifty leaves may sit in one bundle.<br/><em>Only one can keep saying yes.</em></h2><p>Guruji does not begin by asking for the answers. He reads identifying statements from candidate leaves. A wrong answer eliminates a leaf. A possible match must continue to align across your identity and close family details before the full reading is offered.</p><ul><li>Thumbprint narrows the library category</li><li>Candidate bundles are examined by a specialist</li><li>Wrong leaves are eliminated live</li><li>The full reading remains your decision</li></ul><Link className="brahma-primary" href="/journey/brahma-nadi">Reserve the rare search · ₹1,500</Link></div><figure><img className="brahma-direct-image" src="/images/brahma-leaf-verification.webp" alt="A Nadi Guruji comparing a thumb impression with palm-leaf manuscripts" loading="lazy"/></figure></section>
<section className="brahma-chapters"><div><span className="brahma-kicker">The complete arc</span><h2>Sixteen themes. One age-by-age journey.</h2><p>Brahma Nadi is not presented as sixteen disconnected chapter readings. When available on the matched leaf, its themes unfold through the seeker&apos;s life stages—showing how relationships, responsibility, enterprise, public life and spirituality may evolve with age.</p><Link className="brahma-primary" href="/journey/brahma-nadi">Search for my index leaf</Link></div><ol>{chapters.map((c,i)=><li key={c}><span>{String(i+1).padStart(2,"0")}</span>{c}</li>)}</ol></section>
<section className="brahma-pricing"><header><span className="brahma-kicker dark">Transparent decision points</span><h2>Choose the depth only<br/>after your leaf is found.</h2></header><div className="brahma-price-grid"><article className="featured"><small>Step 1 · Begin here</small><h3>Leaf Finding</h3><strong>₹1,500</strong><p>Thumbprint classification, candidate-bundle search and live index-leaf verification.</p><b>Refunded if no matching leaf is found</b><Link href="/journey/brahma-nadi">Begin leaf finding →</Link></article><article><small>After a match · Optional</small><h3>Standard Reading</h3><strong>₹26,500</strong><p>Approximately one hour of detailed, age-by-age guidance focused on your personal life, choices and principal themes.</p><b>For the individual · paid only after a match</b></article><article className="ultra"><small>Deepest format · Optional</small><h3>Ultra Family Reading</h3><strong>₹67,000</strong><p>Up to two hours of deeper age-by-age interpretation, extending beyond you into spouse, children and significant family patterns when present on the leaf.</p><b>You + family depth · paid only after a match</b></article></div></section>
<VideoTestimonials/><section className="brahma-faq"><header><span className="brahma-kicker dark">Before you begin</span><h2>Clear answers to important questions.</h2></header><div>{faqs.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
<section className="brahma-final"><span className="brahma-kicker">The leaf cannot be promised</span><h2>But the search can begin.</h2><p>If a Brahma Nadi leaf matches you, the decision to hear the complete reading remains entirely yours.</p><Link className="brahma-primary" href="/journey/brahma-nadi">Begin Brahma Nadi leaf finding · ₹1,500</Link><small>Full reading is separate. No match means the leaf-finding fee is refunded.</small></section><p className="brahma-tradition-note">Traditional lineage account: associations with Lord Brahma, the Saptarishis and Brahmarshi Vishwamitra reflect Nadi oral tradition, not independently verified historical or scientific fact.</p><SiteFooter showSticky={false}/><div className="brahma-sticky"><Link href="/journey/brahma-nadi">Begin Brahma Nadi leaf search · ₹1,500 →</Link></div></main>}
