import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {SiteHeader,SiteFooter} from '../../../components/SiteChrome';
import {getReviewBlogs} from '../../../lib/review-blogs';
import ReviewVideo from './Video';
import '../../reviews.css';
type Props={params:Promise<{slug:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const p=(await getReviewBlogs()).articles.find(a=>a.slug===slug);if(!p)return{title:'Review story unavailable',robots:{index:false}};return{title:p.title,description:p.description,alternates:{canonical:`/blogs/reviews/${p.slug}`},openGraph:{type:'article',title:p.title,description:p.description,url:`https://www.nadivedas.com/blogs/reviews/${p.slug}`,images:[{url:p.stories[0].posterUrl,alt:p.stories[0].name}]}}}
export default async function Page({params}:Props){const {slug}=await params;const {articles,unavailable}=await getReviewBlogs();const p=articles.find(a=>a.slug===slug);if(!p){if(unavailable)return <main className="new-site"><SiteHeader/><section className="page-body"><h1>This story is temporarily unavailable.</h1><p>Please try again shortly.</p><Link href="/blogs">Browse the journal</Link></section><SiteFooter/></main>;notFound()}const url=`https://www.nadivedas.com/blogs/reviews/${p.slug}`;const json={'@context':'https://schema.org','@type':'BlogPosting',headline:p.title,description:p.description,datePublished:p.date,author:{'@type':'Organization',name:'NadiVedas'},publisher:{'@type':'Organization',name:'NadiVedas'},mainEntityOfPage:url,image:p.stories.map(s=>s.posterUrl),articleSection:'Reviews Blog',inLanguage:'en',wordCount:p.wordCount};return <main className="new-site review-article"><SiteHeader/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(json).replace(/</g,'\\u003c')}}/><header className="review-article-hero"><nav aria-label="Breadcrumb"><Link href="/blogs">Blogs</Link> / <Link href="/blogs/reviews">Reviews Blog</Link></nav><span className="kicker">{p.theme}</span><h1>{p.title}</h1><p>{p.description}</p><div className="review-author">NadiVedas Editorial · <time dateTime={p.date}>{p.date}</time> · {Math.ceil(p.wordCount/200)} min read</div><div className="review-faces">{p.stories.map(s=><a href={`#story-${s.sourceId}`} key={s.sourceId}><img src={s.posterUrl} alt=""/><span>{s.name}</span></a>)}</div></header><article className="review-article-body"><div className="review-intro">{p.intro.map((x,i)=><p key={i}>{x}</p>)}</div>{p.stories.map((s,i)=><section className="review-story" id={`story-${s.sourceId}`} key={s.sourceId}><ReviewVideo story={s}/><div><span className="review-chapter">STORY {String(i+1).padStart(2,'0')}</span><h2>{s.heading}</h2>{s.paragraphs.map((x,j)=><p key={j}>{x}</p>)}</div></section>)}<section className="review-conclusion"><h2>What these experiences invite you to consider</h2>{p.conclusion.map((x,i)=><p key={i}>{x}</p>)}<p className="review-context">These are personal experiences of palm-leaf consultations. They do not guarantee outcomes or describe the separate birth-chart PDF collection.</p><Link className="lux-btn" href="/journey">Explore palm-leaf finding</Link><Link className="review-more-link" href="/reviews">Watch more seeker experiences</Link></section></article><section className="review-related"><h2>More voices. More perspectives.</h2>{articles.filter(a=>a.slug!==p.slug).slice(0,3).map(a=><Link key={a.slug} href={`/blogs/reviews/${a.slug}`}>{a.title}</Link>)}<Link href="/blogs/reviews">Explore all review stories</Link></section><SiteFooter/></main>}
