import type {Metadata} from 'next';
import {SiteHeader,SiteFooter} from '../components/SiteChrome';
import {nadiPrices} from '../lib/nadis';
import {LocalizedPrice} from '../components/LocalizedPrice';
import AffiliateForm from './AffiliateForm';
import './affiliate.css';
export const metadata:Metadata={title:'Become an Affiliate Partner',description:'Introduce your community to NadiVedas. Apply to become an approved affiliate partner and earn commissions on eligible paid referrals.',alternates:{canonical:'https://www.nadivedas.com/affiliate'}};
export default function AffiliatePage(){return <main className="affiliate-page"><SiteHeader/><section className="affiliate-hero"><div className="affiliate-hero-copy"><span className="af-eyebrow">THE NADIVEDAS PARTNER CIRCLE</span><h1>A thoughtful introduction.<br/><em>A rewarding connection.</em></h1><p>Your community already turns to you for guidance. Introduce interested seekers to NadiVedas and earn commissions when your referrals make eligible paid bookings.</p><a className="af-button" href="#apply">Apply to become a partner <span>↗</span></a><small>Personally reviewed applications · Your own referral link</small></div><div className="affiliate-art"><img src="/images/shiva-clean.webp" alt="Artwork representing the Shiva Nadi tradition"/><div><span>SHARE WITH CARE</span><p>Some journeys begin<br/>with someone you trust.</p></div></div></section>
<div className="af-audience"><span>FOR PEOPLE WHO BRING COMMUNITIES TOGETHER</span><p>Astrologers <i>✦</i> Tarot readers <i>✦</i> Spiritual practitioners <i>✦</i> Community organisers</p></div>
<section className="af-section af-value"><div><span className="af-eyebrow">YOUR RELATIONSHIPS. A NEW OPPORTUNITY.</span><h2>Recommend with confidence.<br/><em>Let us handle the reading.</em></h2></div><div className="af-value-copy"><p>You make the introduction. NadiVedas guides the seeker through the leaf search, live matching and optional full reading. Your partner dashboard helps you follow the bookings that come through your link.</p><div className="af-benefits"><article><b>01</b><h3>A link that belongs to you</h3><p>A personal love.nadivedas.com referral link, activated after approval.</p></article><article><b>02</b><h3>Earn on paid referrals</h3><p>Referral commissions on eligible leaf-search and full-reading payments. Terms are shared with approved partners.</p></article><article><b>03</b><h3>Keep track with clarity</h3><p>See your referred bookings, payment status and accrued commissions in one place.</p></article></div></div></section>
<section className="af-how af-section"><span className="af-eyebrow">A SIMPLE WAY TO BEGIN</span><h2>From your application<br/>to your first introduction.</h2><div className="af-steps">{[['Apply','Tell us about your work, community and how you would introduce NadiVedas.'],['Get approved','Our team reviews your profile. Once accepted, your partner login and referral link become active.'],['Share and earn','Share with interested people. Eligible paid bookings appear in your dashboard.']].map(([title,copy],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
<section className="af-section" id="pricing"><span className="af-eyebrow">KNOW WHAT YOU ARE RECOMMENDING</span><h2>Two steps.<br/><em>Clear customer pricing.</em></h2><p className="af-intro">The search comes first. A full reading is a separate, optional purchase after a verified match.</p><div className="af-price-intro"><article><span>STEP 01</span><h3>Find & verify the index leaf</h3><strong><LocalizedPrice inr={999} kind="leaf"/></strong><p>General guided search entry price. Lineage-specific entry prices appear below. The search fee is refunded if no matching leaf is found.</p></article><article><span>STEP 02</span><h3>Choose an optional full reading</h3><p>After a successful match, the seeker can choose the available reading for their Nadi. See the Standard and Ultra prices below.</p><small>Customer prices, not partner earnings. Checkout confirms applicable regional pricing.</small></article></div><div className="af-prices"><table><thead><tr><th>Nadi tradition</th><th>Step 1 · Search</th><th>Step 2 · Standard</th><th>Step 2 · Ultra</th></tr></thead><tbody>{nadiPrices.map(n=><tr key={n.id}><th>{n.name}</th><td><LocalizedPrice inr={n.id==='brahma'?1500:1001} kind="leaf" nadiId={n.id}/></td><td><LocalizedPrice inr={n.price}/></td><td><LocalizedPrice inr={n.ultra}/></td></tr>)}</tbody></table></div></section>
<section className="af-apply af-section" id="apply"><div><span className="af-eyebrow">LET’S MAKE A MEANINGFUL CONNECTION</span><h2>Your community.<br/><em>Your next chapter.</em></h2><p>You do not need a large following. Tell us who you reach and why NadiVedas would be a thoughtful recommendation for them.</p><div className="af-application-note"><b>Every application receives a review.</b><p>Submitting this form does not automatically make you a partner. Your login and referral link activate only after approval.</p></div><a href="https://love.nadivedas.com/partner-login">Already approved? Sign in →</a></div><AffiliateForm/></section>
<section className="af-section af-faq"><span className="af-eyebrow">BEFORE YOU APPLY</span><h2>A few things to know.</h2>{[['Who can apply?','Astrologers, tarot readers, spiritual practitioners, creators, community organisers and anyone with a relevant, engaged network are welcome to apply. We review every application.'],['When do I earn a commission?','When a customer attributed to your referral makes an eligible payment. A click, enquiry or unpaid booking does not generate commission. Refunded payments are excluded.'],['Where can I see commission details?','Approved partners can sign in to see their commission rate, payment activity and an illustrative earnings calculator before they begin sharing their link. Earnings depend on actual paid bookings and are not guaranteed.'],['How should I share my link?','Recommend NadiVedas to people who welcome your introduction, and disclose your affiliate relationship. Unsolicited bulk messaging, purchased backlinks and misleading or guaranteed-outcome claims are not permitted.'],['Will I perform the Nadi reading?','NadiVedas handles the service. As a partner, your role is to introduce interested seekers and explain the process accurately.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section><SiteFooter showSticky={false}/></main>}
