'use client';
import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import ReportOrder from './report-order';
const CheckoutContext=createContext<()=>void>(()=>{});
export function ReportExperience({children}:{children:ReactNode}){const dialog=useRef<HTMLDialogElement>(null);return <CheckoutContext.Provider value={()=>dialog.current?.showModal()}>{children}<dialog className="nr-checkout" ref={dialog} onClick={e=>{if(e.target===dialog.current)dialog.current.close()}}><button className="nr-close" aria-label="Close order form" onClick={()=>dialog.current?.close()}>×</button><div className="nr-checkout-top"><span>YOUR PERSONAL NADI COLLECTION</span><h2>One step closer to your answers.</h2><p><s>₹11,697</s> <strong>₹1,539</strong></p></div><ReportOrder/></dialog></CheckoutContext.Provider>}
export function BuyButton({children='Get my report',className=''}:{children?:ReactNode;className?:string}){const open=useContext(CheckoutContext);return <span className="nr-buy-group"><button className={`nr-buy ${className}`} onClick={open}><strong>{children}</strong></button><small className="nr-cta-tagline">Three Nadi readings. One deeper understanding.</small></span>}
const chapters=[
 ['Your life blueprint','The patterns behind your journey','Begin with your birth chart, planetary positions and the themes that connect your personality, ambitions and relationships.',['Your birth-chart foundations','Planetary strengths and influences','Recurring life themes and growth areas'],'01'],
 ['Career & money','Give your ambition a clearer direction','Explore how your chart describes work, responsibility, earning patterns and the ways you approach opportunity.',['Career and business tendencies','Wealth-related combinations','Periods to reflect, prepare and act'],'02'],
 ['Love & family','Understand how you connect','Read the relationship and family themes in your chart with attention to communication, expectations and personal growth.',['Partnership and marriage themes','Family and children-related indications','Emotional patterns and connection'],'03'],
 ['Timing & dashas','See the larger season you are in','Bring planetary periods and annual outlooks together, so individual themes sit within a longer view of your life.',['Mahadasha and sub-period tables','Year-by-year perspectives','Longer five-year outlooks'],'04'],
 ['Strengths & yogas','Recognise what you can build on','Look beyond a single prediction. Explore supportive combinations, areas that need patience, and the strengths you can develop.',['Planetary strength analysis','Yogas explained in context','Chandra bala and Tara bala'],'05'],
 ['Remedies & guidance','Turn reflection into a next step','Explore optional spiritual practices and chart-based suggestions, explained with a constructive and encouraging tone.',['Puja and devotional suggestions','Gemstone and rudraksha indications','Practical prompts for reflection'],'06']
];
export function InsideChapters(){const [index,setIndex]=useState(0),c=chapters[index];return <div className="nr-explorer"><div className="nr-tabs" role="tablist" aria-label="Explore report chapters">{chapters.map((c,i)=><button key={String(c[0])} role="tab" aria-selected={i===index} aria-controls="nr-chapter-panel" id={`nr-tab-${i}`} onClick={()=>setIndex(i)}><ReportIcon index={i}/>{String(c[0])}</button>)}</div><div id="nr-chapter-panel" role="tabpanel" aria-labelledby={`nr-tab-${index}`} className="nr-chapter-panel"><div><span className="nr-eyebrow">INSIDE YOUR REPORT · {String(c[4])}</span><h3>{String(c[1])}</h3><p>{String(c[2])}</p><ul>{(c[3] as string[]).map(x=><li key={x}>{x}</li>)}</ul><BuyButton>Make this reading yours</BuyButton></div><div className="nr-report-page" aria-hidden="true"><div className="nr-page-brand">NADI VEDAS <span>✦</span></div><small>YOUR PERSONAL READING</small><h4>{String(c[0])}</h4><svg viewBox="0 0 200 200" fill="none"><path d="M10 10H190V190H10ZM10 10L190 190M190 10L10 190M100 10L190 100L100 190L10 100Z" stroke="currentColor" strokeWidth="1"/><text x="93" y="60">☉</text><text x="43" y="108">☽</text><text x="140" y="108">♃</text><text x="92" y="157">♀</text></svg><b>Your chart. A connected reading.</b><div className="nr-page-lines"><i/><i/><i/><i/></div><small>NADI VEDAS · {String(c[4])}</small></div></div></div>}

const iconPaths=[
 'M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M3 7h18v13H3zM3 12a20 20 0 0 0 18 0M10 12h4v3h-4z',
 'M3 3v18h18M7 15l4-5 4 2 6-8M16 4h5v5',
 'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8z',
 'M3 10l9-7 9 7v11H3zM9 21v-8h6v8',
 'M12 3a9 9 0 1 1-9 9 9 9 0 0 1 9-9zM12 7v5l3 2',
 'M12 3l8 4v5c0 5-8 9-8 9s-8-4-8-9V7zM8 12l3 3 5-6'
];
export function ReportIcon({index}:{index:number}){return <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={iconPaths[index%iconPaths.length]}/></svg>}
const highlights=[['Three readings, one collection','Bhrigu Nandi Nadi · Chandra Kala · Dhruva Nadi'],['Made for your questions','Career · relationships · money · life direction'],['Made personal, delivered to you','Your chosen language · Email and WhatsApp within 48 hours'],['One payment. Your own reading.','₹1,539 for your personal report collection']];
export function OfferHighlights(){const [index,setIndex]=useState(0),[paused,setPaused]=useState(false);useEffect(()=>{if(paused||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const timer=window.setInterval(()=>setIndex(i=>(i+1)%highlights.length),6000);return()=>clearInterval(timer)},[paused]);return <aside className="nr-offer-highlights" aria-label="Report offer highlights"><span className="nr-highlight-label">IN YOUR COLLECTION</span><div><strong>{highlights[index][0]}</strong><p>{highlights[index][1]}</p></div><div className="nr-highlight-controls"><button onClick={()=>setIndex(i=>(i+1)%highlights.length)} aria-label="Next offer highlight">Next</button><button onClick={()=>setPaused(!paused)} aria-label={paused?'Play offer highlights':'Pause offer highlights'}>{paused?'Play':'Pause'}</button></div></aside>}
