import type { Metadata } from 'next';
import {SiteHeader,SiteFooter} from '../components/SiteChrome';
import {ReportExperience,BuyButton,InsideChapters,OfferHighlights,ReportIcon} from './experience';
import {VideoTestimonials} from '../components/VideoTestimonials';
import './reports.css';
export const metadata:Metadata={title:'Your Personal Nadi Report Collection | Nadi Vedas',description:'Bhrigu Nandi Nadi, Chandra Kala and Dhruva Nadi in one personal report collection for ₹1,539.',alternates:{canonical:'https://www.nadivedas.com/pdf-reports'}};
const questions=[['01','Career & purpose','Where does your natural ability meet meaningful work?','↗'],['02','Money & growth','What patterns shape the way you build and protect wealth?','◇'],['03','Love & marriage','What can you understand about connection and compatibility?','♡'],['04','Family & belonging','How can you bring more awareness to the relationships that matter?','⌂'],['05','Life’s turning points','Which periods invite movement, patience or a fresh beginning?','◷'],['06','Your inner strengths','What is already within you—and ready to be developed?','✧']];
const faq=[['What exactly will I receive?','A personalized PDF collection bringing together Bhrigu Nandi Nadi, Chandra Kala and Dhruva Nadi readings, chart foundations, planetary periods, yogas, strengths and guidance.'],['When will my report arrive?','Your report will be delivered to your email and WhatsApp within 48 hours of confirmed payment. Keep your private order link to check its progress.'],['Which languages are available?','Choose English, Hindi, Telugu, Tamil, Kannada or Marathi when you enter your birth details.'],['What details do you need?','Your name, email, WhatsApp number, gender, date of birth, exact time of birth and birth city, state and country. If you do not know your birth time, contact our team before ordering.'],['Is this a physical palm-leaf reading?','No. This is a personalized digital report based on your birth details, bringing together three Nadi perspectives.'],['Can I correct my birth details?','Please email support@nadivedas.com promptly with your order reference. Changes after preparation may require a new calculation.']];
function Price(){return <div className="nr-price"><s>₹11,697</s><strong>₹1,539</strong><span>Total savings ₹10,158</span></div>}
export default function ReportsPage(){return <div className="pdf-page nr-page"><ReportExperience><SiteHeader showBooking={false}/><div className="nr-ribbon">YOUR PERSONAL NADI COLLECTION</div><main>
<section className="nr-hero"><div className="nr-wrap nr-hero-grid"><div><p className="nr-eyebrow">ANCIENT PERSPECTIVES. YOUR NEXT CHAPTER.</p><h1>Your story has<br/>more chapters.<br/><em>Meet them with clarity.</em></h1><p className="nr-hero-lead">The patterns behind your past. The strengths within you. The possibilities ahead.</p><p className="nr-hero-copy">Explore <b>Bhrigu Nandi Nadi, Chandra Kala and Dhruva Nadi</b> in a personal report that connects your questions about career, relationships and life’s changing seasons.</p><Price/><p className="nr-bundle-value">₹11,697 stated value · Three personal readings</p><BuyButton>Get my personal report</BuyButton><p className="nr-assurance">One-time purchase · No subscription</p></div><div className="nr-hero-visual"><div className="nr-orbit" aria-hidden="true">✦</div><img src="/images/nadi-report-collection.png" alt="The Nadi Vedas Bhrigu Nandi Nadi, Chandra Kala and Dhruva Nadi report collection" fetchPriority="high"/><div className="nr-visual-caption"><span>THREE NADI PERSPECTIVES</span><p>One life. A deeper understanding.</p></div></div></div></section>
<div className="nr-benefits"><div><b>3</b><span>Nadi perspectives</span></div><div><b>48h</b><span>Report delivery</span></div><div><b>6</b><span>Language choices</span></div><div><b>1</b><span>Personal collection</span></div></div>
<VideoTestimonials reportOffer/><OfferHighlights/><section className="nr-india"><div className="nr-wrap nr-india-grid"><div><p className="nr-eyebrow">ROOTED IN INDIA. ACCESSIBLE FROM ANYWHERE.</p><h2>Your next chapter.<br/><em>From wherever you are.</em></h2><p>From Hyderabad and Chennai to Mumbai and Delhi, explore your Nadi report from home. Choose your language. Bring your questions. Take your next step with us.</p><div className="nr-india-points"><span>6 report languages</span><span>Delivered online</span><span>Personal support</span></div><BuyButton>Create my report · ₹1,539</BuyButton></div><div><img src="/images/nadi-india-online.svg" alt="Map depicting India’s claimed boundaries, including Lakshadweep and the Andaman and Nicobar Islands" loading="lazy"/><p className="nr-map-caption">AVAILABLE ONLINE ACROSS INDIA</p><a className="nr-map-source" href="https://github.com/datameet/maps/tree/master/Country" target="_blank" rel="noreferrer">Map geometry: DataMeet · CC0</a></div></div></section><section className="nr-questions"><div className="nr-wrap"><div className="nr-center"><p className="nr-eyebrow">FOR THE QUESTIONS YOU KEEP COMING BACK TO</p><h2>“What does my next<br/><em>chapter hold?”</em></h2><p>Start with what matters to you. Your reading brings these parts of life into one connected perspective.</p></div><div className="nr-question-grid">{questions.map(([n,t,p])=><article key={n}><span className="nr-question-icon"><ReportIcon index={Number(n)-1}/></span><small>{n}</small><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
<section className="nr-wrap"><div className="nr-center"><p className="nr-eyebrow">YOUR COLLECTION, EXPLAINED</p><h2>Three traditions.<br/><em>A richer view of you.</em></h2><p>Each reading offers another way to explore your life. Together, they give you more to reflect on, connect and revisit.</p></div><div className="nr-traditions">{[['01','Bhrigu Nandi Nadi','The patterns that connect your life','Explore planetary relationships and their interpretations across your work, relationships, ambitions and recurring life themes.','☉','₹4,999'],['02','Chandra Kala Nadi','The rhythm of your changing seasons','Look at the timing of your life through periods and transitions, with yearly themes and longer-range perspectives.','☾','₹3,999'],['03','Dhruva Nadi','Another layer of personal insight','Explore a complementary Nadi perspective on your chart, motivations and the experiences that shape your direction.','✦','₹2,699']].map(([n,t,h,p,s,value])=><article key={n}><div className="nr-tradition-symbol">{s}</div><small>READING {n}</small><h3>{t}</h3><h4>{h}</h4><p>{p}</p><div className="nr-tradition-value"><small>STATED READING VALUE</small><s>{value}</s><b>Included ✓</b></div></article>)}</div></section>
<section className="nr-inside"><div className="nr-wrap"><div className="nr-section-head"><div><p className="nr-eyebrow">OPEN UP YOUR PERSONAL REPORT</p><h2>More than predictions.<br/><em>Perspective you can use.</em></h2></div><p>Explore the chapters below. Your final reading is prepared from your birth details, in your chosen language.</p></div><InsideChapters/></div></section>
<section className="nr-wrap nr-time"><div><p className="nr-eyebrow">A LIFE DOESN’T FIT INTO ONE YEAR</p><h2>See the moment.<br/><em>Understand the season.</em></h2><p>Your report connects near-term themes with the longer planetary periods behind them. Return to it as your circumstances evolve.</p><BuyButton>Explore my life’s chapters</BuyButton></div><div className="nr-timeline">{[['01','Your foundations','Begin with the chart’s strengths, patterns and planetary relationships.'],['02','Year by year','Explore annual themes alongside the planetary periods active in those years.'],['03','The longer view','Follow broader five-year chapters, with context for changing priorities and personal growth.']].map(([n,t,p])=><article key={n}><b>{n}</b><div><h3>{t}</h3><p>{p}</p></div></article>)}</div></section>
<section className="nr-wrap nr-offer-section"><div className="nr-offer-copy"><p className="nr-eyebrow">EVERYTHING COMES TOGETHER HERE</p><h2>One collection.<br/><em>Many reasons to<br/>come back to it.</em></h2><p>A reading for your questions today, and a reference for the chapters still unfolding.</p><div className="nr-language-list">{['English','हिन्दी','తెలుగు','தமிழ்','ಕನ್ನಡ','मराठी'].map(l=><span key={l}>{l}</span>)}</div><p className="nr-fine">Choose your preferred language when you order.</p></div><div className="nr-offer-card"><div className="nr-offer-tag">THE COMPLETE NADI VEDAS COLLECTION</div><h3>Your personal Nadi report</h3><div className="nr-value-stack"><p><span>Three Nadi readings</span><b>₹11,697</b></p><p><span>Today’s collection price</span><b>₹1,539</b></p><p><span>Your savings</span><b>₹10,158</b></p></div><Price/><ul>{['Bhrigu Nandi Nadi reading','Chandra Kala + Dhruva Nadi readings','Birth chart & planetary positions','Dashas, yogas & planetary strengths','Yearly themes & longer-range chapters','Remedies & constructive guidance','Email + WhatsApp delivery within 48 hours'].map(t=><li key={t}><span>✓</span>{t}</li>)}</ul><BuyButton>Create my report · ₹1,539</BuyButton><p className="nr-assurance">Secure payment via PayU · One-time purchase</p></div></section>
<section className="nr-how"><div className="nr-wrap"><div className="nr-center"><p className="nr-eyebrow">SIMPLE FROM THE FIRST STEP</p><h2>Your questions. Your details.<br/><em>Your personal reading.</em></h2></div><div className="nr-how-grid">{[['01','Make it personal','Click Get my report and enter your birth details and preferred language.'],['02','Complete your order','Pay ₹1,539 securely through PayU.'],['03','Let us prepare it','Your personal collection is prepared using the birth information you shared.'],['04','Meet your next chapter','Receive your report by email and WhatsApp within 48 hours. Read at your own pace.']].map(([n,t,p])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{p}</p></article>)}</div></div></section>
<section className="nr-wrap nr-faq"><div><p className="nr-eyebrow">A LITTLE CLARITY, BEFORE YOU BEGIN</p><h2>Your questions,<br/><em>answered.</em></h2><p>Need a hand?<br/><a href="mailto:support@nadivedas.com">support@nadivedas.com</a></p></div><div>{faq.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
<section className="nr-final"><div className="nr-wrap"><span className="nr-final-star">✦</span><p className="nr-eyebrow">GROWING EVERY DAY. ONE CHAPTER AT A TIME.</p><h2>Your future is still unfolding.<br/><em>Get to know your possibilities.</em></h2><Price/><BuyButton>Begin my personal reading</BuyButton><p>Three Nadi perspectives. One personal collection.</p><small>Astrology offers interpretive guidance, not guaranteed outcomes. Your choices and circumstances matter.</small></div></section>
</main><SiteFooter showSticky={false}/><div className="nr-mobile-buy"><div><s>₹11,697</s><strong>₹1,539</strong><small>Three personal Nadi readings</small></div><BuyButton>Get my report</BuyButton></div></ReportExperience></div>}
