import {env} from "cloudflare:workers";

let readyPromise:Promise<unknown>|null=null;
function ready(){if(!readyPromise)readyPromise=env.DB.batch([
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS funnel_events (id TEXT PRIMARY KEY,visitor_id TEXT NOT NULL,lead_id TEXT NOT NULL DEFAULT '',event TEXT NOT NULL,path TEXT NOT NULL DEFAULT '',referrer TEXT NOT NULL DEFAULT '',created_at INTEGER NOT NULL)`),
  env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_funnel_events_event_visitor ON funnel_events(event,visitor_id)"),
  env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_funnel_events_created_at ON funnel_events(created_at)")
]).catch(error=>{readyPromise=null;throw error});return readyPromise}

const allowed=new Set(["page_view","page_exit","scroll_depth","homepage_view","leaf_finding_cta_click","journey_view","details_submitted","payment_started","payment_success","contact_saved","whatsapp_confirmation_opened","whatsapp_confirmed","nadi_selected","thumbprint_uploaded","timeslot_selected"]);
const privateJourneyEvents=new Set(["NadiPageView","NadiBookingClick","NadiExploreClick","NadiDetailsSubmitted","LeafFindingPaid","LeafFindingPaymentFailed","JourneyStepView","NadiSelected","ThumbprintUploaded","PreferredTimeSelected","WhatsAppConfirmed"]);
for(const event of privateJourneyEvents)allowed.add(event);
type EventContext={sessionId?:string;pageViewId?:string;title?:string;landingPath?:string;scrollDepth?:number;engagedSeconds?:number;exitReason?:string;utmSource?:string;utmMedium?:string;utmCampaign?:string;utmContent?:string;utmTerm?:string;gclid?:string;fbclid?:string;device?:string;screen?:string;ipHash?:string;maskedIp?:string;country?:string};
function trimmed(value:unknown,size:number){return String(value||"").slice(0,size)}
async function ipIdentity(request:Request){const ip=request.headers.get("cf-connecting-ip")||"",country=request.headers.get("cf-ipcountry")||"";if(!ip)return {ipHash:"",maskedIp:"",country};const runtime=env as unknown as {LEAD_INGEST_SECRET?:string};const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(runtime.LEAD_INGEST_SECRET||"nadi-visitor"),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const signature=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(ip));const ipHash=Array.from(new Uint8Array(signature),byte=>byte.toString(16).padStart(2,"0")).join("");const maskedIp=ip.includes(":")?`${ip.split(":").slice(0,3).join(":")}:…`:`${ip.split(".").slice(0,3).join(".")}.x`;return {ipHash,maskedIp,country}}

export async function recordFunnelEvent(event:string,visitorId:string,leadId="",path="/journey",referrer="",context:EventContext={}){if(!allowed.has(event)||!visitorId)return;const id=crypto.randomUUID(),createdAt=Date.now();await ready();await env.DB.prepare("INSERT INTO funnel_events(id,visitor_id,lead_id,event,path,referrer,created_at) VALUES(?,?,?,?,?,?,?)").bind(id,visitorId.slice(0,80),leadId.slice(0,80),event,path.slice(0,300),referrer.slice(0,500),createdAt).run()}

export async function POST(request:Request){const body=await request.json().catch(()=>({})) as EventContext&{visitorId?:string;event?:string;leadId?:string;path?:string;referrer?:string};if(!body.visitorId||!body.event||!allowed.has(body.event))return Response.json({error:"Invalid event"},{status:400});const network=await ipIdentity(request);await recordFunnelEvent(body.event,body.visitorId,body.leadId,body.path,body.referrer,{sessionId:trimmed(body.sessionId,80),pageViewId:trimmed(body.pageViewId,80),title:trimmed(body.title,200),landingPath:trimmed(body.landingPath,500),scrollDepth:Math.min(100,Math.max(0,Number(body.scrollDepth||0))),engagedSeconds:Math.min(7200,Math.max(0,Number(body.engagedSeconds||0))),exitReason:trimmed(body.exitReason,30),utmSource:trimmed(body.utmSource,120),utmMedium:trimmed(body.utmMedium,120),utmCampaign:trimmed(body.utmCampaign,200),utmContent:trimmed(body.utmContent,200),utmTerm:trimmed(body.utmTerm,200),gclid:trimmed(body.gclid,200),fbclid:trimmed(body.fbclid,200),device:trimmed(body.device,30),screen:trimmed(body.screen,30),...network});
  // Mirror public website events into the old CRM analytics store. Both the main
  // site and LP use the same persistent nv_vid cookie, so COUNT(DISTINCT
  // session_id) is a deduplicated person count across the two properties.
  if(!privateJourneyEvents.has(body.event))await fetch("https://nadi-ai.pages.dev/api/public-data",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({resource:"track-event",payload:{event:body.event,path:body.path||"/",label:"nadivedas.com",session_id:body.visitorId,referrer:body.referrer||""}})}).catch(()=>undefined);
  return Response.json({ok:true},{status:202})}

export async function GET(request:Request){const runtime=env as unknown as {LEAD_INGEST_SECRET?:string};if(!runtime.LEAD_INGEST_SECRET||request.headers.get("x-analytics-secret")!==runtime.LEAD_INGEST_SECRET)return Response.json({error:"Unauthorized"},{status:401});await ready();const days=Math.min(365,Math.max(1,Number(new URL(request.url).searchParams.get("days")||30))),since=Date.now()-days*86400000;const rows=(await env.DB.prepare("SELECT event,COUNT(DISTINCT visitor_id) unique_visitors,COUNT(*) total_events FROM funnel_events WHERE created_at>=? GROUP BY event").bind(since).all()).results;return Response.json({days,rows,generatedAt:Date.now()},{headers:{"cache-control":"no-store"}})}
