import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { SiteHeader, SiteFooter } from "../../components/SiteChrome";
import { nadiPrices } from "../../lib/nadis";

export const metadata: Metadata = { title: "Choose Your Nadi Palm-Leaf Tradition", description: "Compare Shiva Vakya, Brahma, Nandi, Kakabhushundi, Agastya and other Nadi traditions before beginning a ₹999 leaf search.", alternates: { canonical: "/collections/all" } };
const featured = new Set(["shiva", "brahma", "nandi"]);
const slug: Record<string,string> = { shiva:"shiva-vakya-nadi",nandi:"nandi-nadi",kaka:"kaka-bhushundi-nadi",vasishta:"vasishtha-nadi",thirumoolar:"thirumoolar-nadi",bhogar:"bhogar-nadi",dhanvantari:"dhanvantari-nadi",shukra:"shukra-nadi",bhrigu:"bhrigu-nadi",atri:"atri-nadi",agastya:"agastya-nadi",brahma:"brahma-nadi" };
export default function Page(){const first=nadiPrices.filter(n=>featured.has(n.id));const rest=nadiPrices.filter(n=>!featured.has(n.id));return <main className="new-site nadi-collection"><SiteHeader/><header className="collection-hero"><span>Choose the voice of your reading</span><h1>Twelve Nadi traditions.<br/><em>Three exceptional places to begin.</em></h1><p>Every lineage carries a different traditional character. Compare the emphasis, then find and verify the index leaf before choosing any continuation-bundle reading.</p><Link className="lux-btn" href="/journey">Let NadiVedas guide my choice <b>→</b></Link><small>₹999 index-leaf finding · Refunded if no index leaf is found</small></header>
  <section className="featured-nadis"><header><span>Featured lineages</span><h2>The depth seekers ask for most</h2><p>Shiva Vakya, Brahma and Nandi receive greater prominence because they offer distinct routes into complete-life, deep-destiny and worldly-direction questions.</p></header><div>{first.map((n,i)=><Link href={`/products/${slug[n.id]}`} className={`featured-nadi-card ${n.id}`} key={n.id}><Image src={n.image} alt={`${n.name} traditional lineage illustration`} fill unoptimized sizes="(max-width:900px) 100vw, 33vw"/><i/><span>0{i+1} · {n.tag}</span><section><small>{n.sage}</small><h2>{n.name}</h2><p>{n.focus}</p><b>Explore {n.name} →</b></section></Link>)}</div></section>
  <section className="all-nadis"><header><span>Explore the full library</span><h2>Find the lineage that speaks to your question</h2></header><div>{rest.map(n=><Link href={`/products/${slug[n.id]}`} className="nadi-shop-card" key={n.id}><div><Image src={n.image} alt={`${n.name} lineage illustration`} fill unoptimized sizes="(max-width:900px) 100vw, 25vw"/></div><section><small>{n.tag} · {n.sage}</small><h3>{n.name}</h3><p>{n.focus}</p><b>Discover this Nadi →</b></section></Link>)}</div></section>
  <section className="collection-promise"><span>Find the index leaf first. Choose freely.</span><h2>No continuation-bundle payment before the index leaf is verified.</h2><p>₹999 covers Guruji’s search for and live Google Meet verification of the index leaf—the first or index page of the record. The separate continuation bundle contains the future-prediction reading, starts from ₹11,800 and remains optional after a successful match.</p><Link className="gold-outline" href="/journey">Begin the guided Nadi journey →</Link></section><SiteFooter/></main>}
