import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound, permanentRedirect } from "next/navigation";
import { SiteHeader, SiteFooter } from "../../components/SiteChrome";
import { nadiPrices } from "../../lib/nadis";

const slugs: Record<string, string> = {
  "shiva-vakya-nadi": "shiva", "shiva-nadi": "shiva", "nandi-nadi": "nandi",
  "kaka-bhushundi-nadi": "kaka", "kakabhushundi-nadi": "kaka", "vasishtha-nadi": "vasishta",
  "thirumoolar-nadi": "thirumoolar", "bhogar-nadi": "bhogar", "dhanvantari-nadi": "dhanvantari",
  "shukra-nadi": "shukra", "bhrighu-nadi": "bhrigu", "bhrigu-nadi": "bhrigu",
  "atri-nadi": "atri", "agastya-nadi": "agastya", "brahma-nadi": "brahma",
};

const profile: Record<string, { eyebrow: string; headline: string; lead: string; character: string; suited: string[]; moments: string[]; featured?: boolean }> = {
  shiva: { featured: true, eyebrow: "The signature complete-life lineage", headline: "When one answer is not enough, seek the whole pattern.", lead: "Shiva Vakya Nadi is presented through the sacred dialogue of Lord Shiva and Parvati. It is NadiVedas’ most expansive choice for seekers who want relationships, career, prosperity, family karma and spiritual direction considered as one connected life story.", character: "Direct · Expansive · Complete", suited: ["A major life crossroads", "Marriage, career and money together", "Deep family and karmic patterns"], moments: ["You want a broad life reading rather than one isolated answer.", "Several areas of life feel connected and need a single frame.", "You are ready for direct traditional language and substantial depth."] },
  brahma: { featured: true, eyebrow: "The rare deep-destiny lineage", headline: "Look beyond events. Explore the design beneath them.", lead: "Brahma Nadi is traditionally associated with Lord Brahma and approached for profound questions of purpose, karmic design and the architecture of a life. It is positioned as the deepest NadiVedas lineage for seekers drawn to rare, all-encompassing perspective.", character: "Rare · Profound · All-encompassing", suited: ["Life purpose and karmic design", "Long-range family destiny", "Spiritual direction at exceptional depth"], moments: ["You are asking why your life follows a repeating pattern.", "Surface-level guidance no longer feels sufficient.", "You want the most extensive lineage option after a verified match."] },
  nandi: { featured: true, eyebrow: "Protective strength and worldly direction", headline: "For the seeker building something that must endure.", lead: "Nandi Nadi carries a protective, steady character in tradition. Seekers often consider it for business, finance, career responsibility and spiritual growth—especially when ambition must be balanced with values and long-term stability.", character: "Rare · Protective · Karmic", suited: ["Business and financial direction", "Leadership and responsibility", "Growth anchored in spiritual values"], moments: ["A career or enterprise decision carries long-term consequences.", "You want prosperity questions held beside duty and discipline.", "You prefer a firm, grounded traditional voice."] },
  kaka: { eyebrow: "Strategic sight across time", headline: "See the decision, the timing and the road beyond it.", lead: "Kakabhushundi Nadi is traditionally linked with the far-seeing sage Kakabhushundi. Its character is strategic and time-aware, attracting seekers focused on career moves, enterprise, high-stakes choices and the longer arc of a decision.", character: "Strategic · Precise · Far-seeing", suited: ["Career and enterprise choices", "Timing-sensitive decisions", "Long-range direction"], moments: ["You face competing paths and need a clearer framework.", "Timing matters as much as the decision itself.", "You value precise, strategic guidance." ] },
  vasishta: { eyebrow: "Wisdom for duty and daily life", headline: "Bring family, responsibility and purpose back into balance.", lead: "Vasishta Nadi is traditionally associated with Sage Vasishta and a balanced, dharmic voice. It suits seekers who want practical direction for family, duty, relationships and the responsibilities that shape an honourable life.", character: "Wise · Balanced · Dharmic", suited: ["Family and household decisions", "Duty, values and relationships", "Grounded life direction"], moments: ["You are carrying responsibility for others.", "Family and personal purpose feel out of balance.", "You want wisdom expressed in practical terms."] },
  thirumoolar: { eyebrow: "The inward Siddha path", headline: "Turn a difficult season into disciplined inner movement.", lead: "Thirumoolar Nadi belongs to the Siddha stream and is traditionally associated with yogic discipline, wellbeing and higher purpose. It appeals to seekers who want spiritual practice and everyday transformation to meet.", character: "Yogic · Healing · Inward", suited: ["Spiritual discipline", "Wellbeing and inner change", "A deeper sense of purpose"], moments: ["You feel called toward sustained spiritual practice.", "A transition is asking you to change from within.", "You want wellbeing discussed without replacing qualified care."] },
  bhogar: { eyebrow: "Transformation through Siddha wisdom", headline: "Meet change with protection, practice and purpose.", lead: "Bhogar Nadi is traditionally associated with the Siddha Bhogar and an alchemical, transformative character. Seekers often explore it for wellbeing, remedy traditions and periods that demand deep personal change.", character: "Alchemical · Healing · Protective", suited: ["Transformative life periods", "Wellbeing and remedy traditions", "Protection and spiritual practice"], moments: ["Old approaches are no longer working.", "You want change framed through Siddha tradition.", "You can hold spiritual practice beside responsible professional care."] },
  dhanvantari: { eyebrow: "Focused restorative guidance", headline: "Approach wellbeing with reflection, care and clear boundaries.", lead: "Dhanvantari Nadi is traditionally associated with restorative and health-focused questions. It may support spiritual reflection around wellbeing, but it never replaces diagnosis, treatment or urgent care from qualified professionals.", character: "Restorative · Focused · Caring", suited: ["Wellbeing reflection", "Health-related spiritual questions", "Protective daily practices"], moments: ["Health concerns have changed how you see your life.", "You want spiritual context without medical promises.", "You value a focused rather than general reading emphasis."] },
  shukra: { eyebrow: "Relationship and abundance themes", headline: "Explore what you value, attract and build together.", lead: "Shukra Nadi carries a refined, relational character in tradition. Seekers are drawn to it for love, marriage, property, prosperity and the way desire and values shape important life choices.", character: "Abundant · Relational · Refined", suited: ["Love and marriage", "Property and prosperity", "Values within partnership"], moments: ["A relationship decision is shaping your future.", "You want to understand prosperity alongside values.", "Home, partnership and resources feel interconnected."] },
  bhrigu: { eyebrow: "Detailed predictive tradition", headline: "Trace the milestones without surrendering your choices.", lead: "Bhrigu Nadi is traditionally associated with detailed destiny timing and a far-seeing style. It attracts seekers curious about major milestones in relationships, finance and direction while preserving personal judgement and free choice.", character: "Predictive · Detailed · Far-seeing", suited: ["Major life milestones", "Relationship and finance timing", "A detailed traditional overview"], moments: ["You are curious about the sequence of major transitions.", "Several milestone decisions are approaching.", "You want detail without treating prediction as certainty."] },
  atri: { eyebrow: "Ancestral blessing and protection", headline: "Understand the family patterns carried into the present.", lead: "Atri Nadi is traditionally associated with Sage Atri and a protective, ancestral quality. Seekers consider it for family karma, blessings, household wellbeing and spiritual steadiness across generations.", character: "Blessed · Ancestral · Protective", suited: ["Family and ancestral patterns", "Household wellbeing", "Spiritual protection and blessings"], moments: ["A family pattern seems to repeat across generations.", "Your question concerns more than one household member.", "You are drawn to a gentle, blessing-oriented lineage."] },
  agastya: { eyebrow: "The clear foundational lineage", headline: "Begin with the life questions that matter most now.", lead: "Agastya Nadi is one of the best-known Nadi traditions and a strong foundational choice. Its practical character makes it approachable for career, marriage, family, finance and an overall introduction to the palm-leaf reading journey.", character: "Foundational · Clear · Practical", suited: ["A first complete Nadi reading", "Career, marriage and family", "Practical life direction"], moments: ["This is your first experience of Nadi astrology.", "You want broad guidance in accessible terms.", "A practical starting point matters more than maximum depth."] },
};

const faq = [
  ["Is this lineage guaranteed to have my leaf?", "No. The ₹999 first stage is a search, and it may end without a match. The search amount is refunded when no matching leaf is found."],
  ["Do I pay for the continuation-bundle reading before matching?", "No. ₹999 covers finding and verifying the index leaf. The separate continuation-bundle reading starts from ₹11,800 and matters only after the index leaf consistently identifies you and you choose to continue."],
  ["Are lineage descriptions scientifically proven?", "No. Sage attributions, karmic themes and predictive meanings belong to Nadi tradition and belief. They are not established scientific findings."],
  ["Can Nadi guidance replace professional advice?", "No. It must not replace qualified medical, legal, financial or mental-health advice."],
] as const;

export function generateStaticParams() { return Object.keys(slugs).map(slug => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const id = slugs[slug]; const item = nadiPrices.find(n => n.id === id); const p = profile[id]; if (!item || !p) return {}; return { title: `${item.name} Palm-Leaf Reading`, description: `${p.lead.slice(0, 150)} Learn the ₹999 leaf-finding process.`, alternates: { canonical: `/products/${slug}` }, openGraph: { type: "website", url: `https://www.nadivedas.com/products/${slug}`, title: `${item.name} Palm-Leaf Reading`, description: p.lead, images: [{ url: item.image, alt: `${item.name} lineage illustration` }] } }; }

export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  if (["book-your-leaf", "book-your-leaf-finding-501-inr", "leaf-finding-session", "nadivedas-step-1-leaf-finding-session"].includes(slug)) permanentRedirect("/journey");
  const id = slugs[slug]; const item = nadiPrices.find(n => n.id === id); const p = profile[id]; if (!item || !p) notFound();
  const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "Service", name: `${item.name} leaf finding and optional reading`, provider: { "@type": "Organization", name: "NadiVedas", url: "https://www.nadivedas.com" }, description: p.lead, areaServed: "Worldwide", url: `https://www.nadivedas.com/products/${slug}` }, { "@type": "FAQPage", mainEntity: faq.map(([q,a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })) }] };
  return <main className={`new-site lineage-landing ${p.featured ? "featured-lineage" : ""}`}><SiteHeader /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <header className="lineage-product-hero"><div className="lineage-product-copy"><span>{p.eyebrow}</span><h1>{item.name}</h1><h2>{p.headline}</h2><p>{p.lead}</p><div><Link className="lux-btn" href={`/journey?interest=${item.id}`}>Search for my {item.name} index leaf <b>→</b></Link><small>₹999 index-leaf finding · Refunded if no index leaf is found</small></div></div><figure><Image src={item.image} alt={`${item.name} traditional lineage illustration`} fill priority unoptimized sizes="(max-width: 900px) 100vw, 42vw" /><figcaption>{item.sage} · Traditional lineage illustration</figcaption></figure></header>
    <section className="lineage-trust-strip"><div><b>₹999</b><span>Index-leaf search</span></div><div><b>Google Meet</b><span>Live index-leaf verification</span></div><div><b>Your choice</b><span>Continuation bundle only after a match</span></div></section>
    <section className="lineage-sales-body"><div className="lineage-intro"><span>The character of this Nadi</span><h2>{p.character}</h2><p>{item.focus}</p></div><div className="lineage-suited"><h2>What seekers come to {item.name} to explore</h2>{p.suited.map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3><p>A focused traditional lens for reflection—never a guaranteed prediction or substitute for your own judgement.</p></article>)}</div>
      <div className="lineage-moments"><section><span>Is this your moment?</span><h2>{item.name} may resonate when…</h2><ul>{p.moments.map(x=><li key={x}>{x}</li>)}</ul></section><aside><small>Begin with evidence, not pressure</small><h3>Your index leaf must identify you first.</h3><p>A clear thumb impression guides Guruji towards candidate bundles. During a live Google Meet session, identifying statements are tested without forcing a match.</p><Link href="/blogs/nadi-astrology-thumb-impression">Understand Nadi thumb-impression matching →</Link></aside></div>
      <div className="lineage-path"><span>How it works</span><h2>Three decisions. Always in the right order.</h2><div><article><b>01</b><h3>Search</h3><p>Pay ₹999, submit a clear thumb impression and let Guruji search the candidate bundles.</p></article><article><b>02</b><h3>Verify the index leaf</h3><p>On Google Meet, Guruji tests the identifying leaf—the first or index page of the record. A non-match remains possible.</p></article><article><b>03</b><h3>Choose the continuation</h3><p>If the index leaf matches, review the separate continuation bundle, scope and fee before choosing the future-prediction reading.</p></article></div></div>
      <div className="lineage-price"><div><small>Only the index-leaf search comes first</small><h2>Find the first page before choosing the rest of the book.</h2><p>₹999 covers finding and verifying the index leaf. The separate continuation-bundle reading contains the future-prediction material, starts from ₹11,800 and varies by lineage and depth.</p></div><Link className="lux-btn" href={`/journey?interest=${item.id}`}>Begin {item.name} leaf finding <span>→</span></Link></div>
      <div className="lineage-faq"><span>Questions before you begin</span><h2>Clear answers, without pressure</h2>{faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div>
      <div className="lineage-related"><Link href="/collections/all">Compare all Nadi traditions</Link><Link href={`/nadis#${item.id}`}>Read the {item.name} lineage overview</Link><Link href="/about#how-it-works">See the complete NadiVedas process</Link></div>
    </section><SiteFooter /></main>;
}
