import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {SiteHeader,SiteFooter} from "../../components/SiteChrome";
import {getJournalPost,journalPosts} from "../../lib/journal";

export function generateStaticParams(){return journalPosts.map(({slug})=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const post=getJournalPost(slug);if(!post)return{};return{title:`${post.title} | NadiVedas Journal`,description:post.description,alternates:{canonical:`/blog/${post.slug}`},openGraph:{title:post.title,description:post.description,type:"article",url:`https://www.nadivedas.com/blog/${post.slug}`}}}

export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const post=getJournalPost(slug);if(!post)notFound();const schema={"@context":"https://schema.org","@type":"Article",headline:post.title,description:post.description,author:{"@type":"Organization",name:"NadiVedas"},publisher:{"@type":"Organization",name:"NadiVedas",url:"https://www.nadivedas.com"},mainEntityOfPage:`https://www.nadivedas.com/blog/${post.slug}`};return <main className="new-site journal-article"><SiteHeader/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><header className="article-hero"><div><Link href="/blog">← Journal</Link><span>{post.category} · {post.readTime}</span><h1>{post.title}</h1><p>{post.description}</p></div></header><article className="article-shell"><aside><span>In this guide</span>{post.sections.map((section,index)=><a key={section.heading} href={`#section-${index+1}`}>{String(index+1).padStart(2,"0")} {section.heading}</a>)}<Link href="/journey">Begin ₹999 index-leaf finding →</Link></aside><div className="article-copy"><p className="article-intro">{post.intro}</p>{post.sections.map((section,index)=><section id={`section-${index+1}`} key={section.heading}><span>{String(index+1).padStart(2,"0")}</span><h2>{section.heading}</h2>{section.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}</section>)}{post.faq&&<section className="article-faq"><span>FAQ</span><h2>Common questions</h2>{post.faq.map(item=><details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</section>}<div className="article-next"><small>The next step is only the index-leaf search</small><h2>Find the first page before choosing the rest of the book.</h2><p>₹999 covers finding and verifying the index leaf and is refunded if no match is found. The separate continuation-bundle reading contains the future-prediction material, starts from ₹11,800 and remains your choice after a successful match.</p><Link href="/journey" className="lux-btn">Begin index-leaf finding <span>→</span></Link></div></div></article><SiteFooter/></main>}
