import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { permanentRedirect } from "next/navigation";
import { SiteHeader, SiteFooter } from "../../components/SiteChrome";

type LegacyPage = { title: string; description: string; heading: string; intro: string; sections: { title: string; body: string }[]; relatedHref: string; relatedLabel: string };

const pages: Record<string, LegacyPage> = {
  "terms-conditions": { title: "Terms and Conditions", description: "Terms governing NadiVedas leaf-finding and traditional palm-leaf reading services.", heading: "Terms and conditions", intro: "These terms explain the nature, limits and responsibilities of using NadiVedas services.", relatedHref: "/refund-policy", relatedLabel: "Read the NadiVedas refund policy", sections: [
    { title: "Nature of the service", body: "NadiVedas facilitates traditional, faith-based palm-leaf searches and interpretative readings for spiritual, cultural and personal reflection. Nadi astrology is not a scientifically validated method and a leaf match or particular outcome is never guaranteed." },
    { title: "Not professional advice", body: "Readings and remedies do not provide medical diagnosis or treatment, legal advice, financial advice or mental-health care. Seek a suitably qualified professional for decisions in those areas, and use emergency services when urgent help is needed." },
    { title: "Index-leaf finding and continuation readings", body: "₹999 covers Guruji's search for and live verification of the index leaf—the first or index page of the record. If it is found, the separate continuation bundle contains the future-prediction reading and starts from ₹11,800. It varies by lineage, depth and scope. The seeker sees the exact option before deciding whether to continue." },
    { title: "Personal responsibility and conduct", body: "You remain responsible for decisions made after a reading. You agree not to misuse the website, interfere with service delivery, reproduce protected recordings without permission or submit information you are not authorised to share." },
    { title: "Payments, intellectual property and changes", body: "Payment processing may be handled by third parties. NadiVedas branding, original site content and service materials remain protected. These terms may be updated when services or legal requirements change. Indian law applies, subject to any mandatory consumer rights." },
  ] },
  "about-us": { title: "About Our Palm-Leaf Reading Approach", description: "Meet NadiVedas and learn why the platform puts transparent leaf matching before any optional reading.", heading: "About NadiVedas", intro: "NadiVedas was created to make the South Indian palm-leaf reading tradition easier to approach online—with clearer stages, calmer decisions and respect for evidence boundaries.", relatedHref: "/about#how-it-works", relatedLabel: "See how NadiVedas leaf finding works", sections: [
    { title: "Why the platform exists", body: "For many seekers, language, distance and uncertainty make a traditional Nadi search difficult to navigate. NadiVedas coordinates the path from thumbprint classification and candidate-bundle search to Guruji's live Google Meet verification of the index leaf, while keeping the separate continuation-bundle reading optional." },
    { title: "What we believe good service requires", body: "A reader should explain the process, allow a genuine non-match and avoid using fear to sell chapters or remedies. A seeker should receive clear scope, pricing, privacy information and room to decide whether to continue." },
    { title: "Tradition and responsible language", body: "Nadi lineages attribute palm-leaf records to sages and sacred sources. We present those accounts as traditional belief rather than scientific proof. Historical claims about a specific manuscript require evidence beyond a reading session." },
    { title: "The first page before the rest of the book", body: "NadiVedas begins with ₹999 index-leaf finding. The index leaf is like the first or index page of a book: it identifies the seeker. The separate continuation bundle contains the future-prediction reading, starts from ₹11,800, varies by lineage and depth, and matters only after a verified match." },
  ] },
  "return-shipping": { title: "Return, Delivery and Refund Information", description: "Understand digital delivery, leaf-search refunds and completed-reading terms for NadiVedas services.", heading: "Return, delivery and refund information", intro: "NadiVedas provides digital coordination and consultation services. No physical product is shipped as part of the standard leaf-finding journey.", relatedHref: "/refund-policy", relatedLabel: "View the complete leaf-finding refund policy", sections: [
    { title: "Digital service delivery", body: "Appointments, matching sessions and readings are normally coordinated online. Meeting information and agreed recordings or summaries are delivered through the contact channel confirmed during booking." },
    { title: "When no index leaf is found", body: "The ₹999 index-leaf finding amount is refunded when Guruji's bundle search and live verification conclude without a matching index leaf, according to the published policy and ordinary payment-processing timelines." },
    { title: "When a service has been completed", body: "A personalised continuation-bundle reading that has already been delivered cannot be physically returned. Before paying, confirm its chapters, language, duration, recording arrangements and fee." },
    { title: "Questions about an outcome", body: "Keep your payment reference and booking contact details. Contact NadiVedas promptly if an appointment, recording or eligible refund needs to be reviewed." },
  ] },
  "privacy-policies": { title: "Privacy Policy for Thumbprints and Readings", description: "How NadiVedas handles contact details, thumb impressions, consultation information and deletion requests.", heading: "Privacy policy", intro: "A thumb impression and a private reading can reveal sensitive information. NadiVedas collects only the information needed to coordinate the requested service and does not sell personal data.", relatedHref: "/privacy", relatedLabel: "Read the current NadiVedas privacy policy", sections: [
    { title: "Information used for the service", body: "Information may include your name, contact details, broad birth-year information, gender, thumb impression, booking records and communications. Payment credentials are handled by payment providers rather than stored as plain site content." },
    { title: "Why information is used", body: "Data supports bundle classification, leaf-search coordination, live matching, translation, service delivery, support, refunds and required business records. Information should not be used to pre-fill a candidate-leaf match." },
    { title: "Limited sharing and retention", body: "Only team members, readers, translators and service providers who need relevant information for delivery should receive it. Records are retained only as long as reasonably needed for service, security and legal obligations." },
    { title: "Your choices", body: "You may ask about access, correction or deletion by contacting support@nadivedas.com. Some records may need to be retained when law, payment disputes or fraud prevention require it." },
  ] },
  "contact": { title: "Contact and Leaf-Finding Support", description: "Contact NadiVedas for questions about ₹999 leaf finding, matching sessions, refunds and online readings.", heading: "Contact NadiVedas", intro: "For help with a leaf search, appointment, payment or recording, contact the team using the details already provided during your booking or email support@nadivedas.com.", relatedHref: "/journey", relatedLabel: "Begin the guided Nadi leaf-finding journey", sections: [
    { title: "Before you contact us", body: "Include your name, booking reference and a short description of the issue. Never send a card PIN, one-time password or unrelated identity document." },
    { title: "Leaf-search questions", body: "Ask about the required thumb impression, matching language, appointment timing, no-match outcome and refund terms before paying. Avoid sending a full personal biography before live matching." },
    { title: "Existing bookings", body: "Use the same verified contact channel through which your appointment was confirmed. This helps the team locate the correct record and reduces impersonation risk." },
  ] },
};

export function generateStaticParams() { return Object.keys(pages).map(slug => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const page = pages[slug]; if (!page) return {}; return { title: page.title, description: page.description, alternates: { canonical: `/pages/${slug}` }, openGraph: { title: page.title, description: page.description, url: `https://www.nadivedas.com/pages/${slug}`, type: "website" } }; }

export default async function LegacyPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; if (slug === "reviews") permanentRedirect("/reviews"); if (slug === "refund-policy") permanentRedirect("/refund-policy"); if (slug === "privacy-policy") permanentRedirect("/privacy"); const page = pages[slug]; if (!page) notFound(); return <main className="new-site"><SiteHeader /><header className="page-hero"><span className="kicker">NadiVedas information</span><h1>{page.heading}</h1><p>{page.intro}</p></header><section className="page-body"><div className="legacy-sections">{page.sections.map(section => <article key={section.title}><h2>{section.title}</h2><p>{section.body}</p></article>)}</div><div className="new-actions"><Link className="lux-btn" href={page.relatedHref}>{page.relatedLabel} <span>→</span></Link></div></section><SiteFooter /></main>; }
